// Static fallback data used when database is not available (e.g., Vercel serverless)
// Expanded to 36 startups with weekly winners and community boards

export interface Startup {
  id: string
  name: string
  slug: string
  tagline: string
  description: string | null
  logo: string | null
  website: string
  twitter: string | null
  linkedin: string | null
  category: string
  stage: string
  teamSize: string
  foundedYear: number | null
  country: string | null
  email: string | null
  upvotes: number
  featured: boolean
  status: string
  createdAt: string
  updatedAt: string
  _count: { votes: number; perks: number }
  logoColor?: string
  weeklyPoints?: number
}

export const fallbackStartups: Startup[] = [
  {
    id: 'fb-1',
    name: 'NeuralForge',
    slug: 'neuralforge',
    tagline: 'AI-powered code review that catches bugs before they ship',
    description: 'NeuralForge uses advanced machine learning models to analyze your codebase in real-time, identifying potential bugs, security vulnerabilities, and performance issues. Compatible with all major IDEs and CI/CD pipelines.',
    logo: null,
    website: 'https://neuralforge.dev',
    twitter: 'neuralforge',
    linkedin: 'neuralforge',
    category: 'AI',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: 'hello@neuralforge.dev',
    upvotes: 342,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 342, perks: 2 },
    logoColor: '#6366F1',
    weeklyPoints: 340,
  },
  {
    id: 'fb-2',
    name: 'PayStream',
    slug: 'paystream',
    tagline: 'Instant cross-border payments for freelancers and SMBs',
    description: 'PayStream eliminates the pain of international payments. Send and receive money in 50+ currencies with zero fees, instant settlement, and transparent exchange rates.',
    logo: null,
    website: 'https://paystream.io',
    twitter: 'paystream',
    linkedin: 'paystream',
    category: 'Finance',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United Kingdom',
    email: 'info@paystream.io',
    upvotes: 287,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-02-10').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 287, perks: 1 },
    logoColor: '#10B981',
    weeklyPoints: 290,
  },
  {
    id: 'fb-3',
    name: 'CloudNest',
    slug: 'cloudnest',
    tagline: 'Deploy infrastructure as code with visual drag-and-drop',
    description: 'CloudNest makes infrastructure management accessible to everyone. Visually design your cloud architecture and get optimized, production-ready infrastructure code.',
    logo: null,
    website: 'https://cloudnest.dev',
    twitter: 'cloudnest',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Germany',
    email: null,
    upvotes: 256,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 256, perks: 1 },
    logoColor: '#F59E0B',
    weeklyPoints: 210,
  },
  {
    id: 'fb-4',
    name: 'MediScan AI',
    slug: 'mediscan-ai',
    tagline: 'AI diagnostic assistant for radiologists and clinicians',
    description: 'MediScan AI accelerates medical imaging diagnostics with FDA-cleared algorithms trained on millions of medical images, detecting anomalies with 97.3% accuracy.',
    logo: null,
    website: 'https://mediscan.ai',
    twitter: 'mediscan_ai',
    linkedin: 'mediscan-ai',
    category: 'AI',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Israel',
    email: null,
    upvotes: 234,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 234, perks: 1 },
    logoColor: '#EF4444',
  },
  {
    id: 'fb-5',
    name: 'LearnLoop',
    slug: 'learnloop',
    tagline: 'Personalized AI tutoring that adapts to every learning style',
    description: 'LearnLoop creates personalized curricula that adapt in real-time based on learning patterns, strengths, and weaknesses. Delivering 1-on-1 tutoring at scale.',
    logo: null,
    website: 'https://learnloop.ai',
    twitter: 'learnloop',
    linkedin: null,
    category: 'AI',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Canada',
    email: null,
    upvotes: 198,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-15').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 198, perks: 0 },
    logoColor: '#8B5CF6',
  },
  {
    id: 'fb-6',
    name: 'GreenGrid',
    slug: 'greengrid',
    tagline: 'Smart energy management platform for commercial buildings',
    description: 'GreenGrid helps commercial property owners reduce energy costs by up to 40% through AI-optimized energy management with IoT sensors and ML algorithms.',
    logo: null,
    website: 'https://greengrid.energy',
    twitter: 'greengrid_energy',
    linkedin: null,
    category: 'Business',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'Netherlands',
    email: null,
    upvotes: 176,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-25').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 176, perks: 0 },
    logoColor: '#22C55E',
  },
  {
    id: 'fb-7',
    name: 'StackBot',
    slug: 'stackbot',
    tagline: 'AI customer support agent trained on your entire documentation',
    description: 'StackBot creates intelligent customer support agents by ingesting your docs, APIs, and knowledge base to provide accurate, contextual answers 24/7.',
    logo: null,
    website: 'https://stackbot.io',
    twitter: 'stackbot',
    linkedin: null,
    category: 'SaaS',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Australia',
    email: null,
    upvotes: 163,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-20').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 163, perks: 0 },
    logoColor: '#0EA5E9',
  },
  {
    id: 'fb-8',
    name: 'ChainVault',
    slug: 'chainvault',
    tagline: 'Institutional-grade DeFi custody and treasury management',
    description: 'ChainVault bridges traditional finance and DeFi with institutional custody, multi-sig security, insurance coverage, and regulatory compliance.',
    logo: null,
    website: 'https://chainvault.finance',
    twitter: 'chainvault_fi',
    linkedin: null,
    category: 'Finance',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Singapore',
    email: null,
    upvotes: 152,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 152, perks: 0 },
    logoColor: '#6D28D9',
  },
  {
    id: 'fb-9',
    name: 'FlowMetrics',
    slug: 'flowmetrics',
    tagline: 'Real-time product analytics with built-in AI insights',
    description: 'FlowMetrics gives product teams AI-driven analytics that go beyond dashboards. Discover behavior patterns, predict churn, and identify growth opportunities.',
    logo: null,
    website: 'https://flowmetrics.com',
    twitter: 'flowmetrics',
    linkedin: null,
    category: 'SaaS',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'France',
    email: null,
    upvotes: 141,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-10').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 141, perks: 0 },
    logoColor: '#F97316',
  },
  {
    id: 'fb-10',
    name: 'HireLogic',
    slug: 'hirelogic',
    tagline: 'AI-powered hiring that eliminates bias and accelerates recruitment',
    description: 'HireLogic transforms hiring with intelligent job descriptions, automated sourcing, bias-free screening, and structured interview guides.',
    logo: null,
    website: 'https://hirelogic.com',
    twitter: 'hirelogic',
    linkedin: null,
    category: 'Business',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 128,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-15').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 128, perks: 0 },
    logoColor: '#14B8A6',
  },
  {
    id: 'fb-11',
    name: 'CyberShield AI',
    slug: 'cybershield-ai',
    tagline: 'Autonomous threat detection and response for SMBs',
    description: 'CyberShield AI provides enterprise-grade cybersecurity for SMBs with autonomous AI agents that monitor your infrastructure 24/7.',
    logo: null,
    website: 'https://cybershield.ai',
    twitter: 'cybershield_ai',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Estonia',
    email: null,
    upvotes: 119,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-20').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 119, perks: 0 },
    logoColor: '#DC2626',
  },
  {
    id: 'fb-12',
    name: 'FreshCart',
    slug: 'freshcart',
    tagline: 'AI-driven grocery delivery with real-time inventory tracking',
    description: 'FreshCart connects consumers directly with local grocery stores. AI optimizes delivery routes, predicts demand, and ensures fresh products arrive within 30 minutes.',
    logo: null,
    website: 'https://freshcart.app',
    twitter: 'freshcart',
    linkedin: null,
    category: 'Business',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'India',
    email: null,
    upvotes: 112,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-25').toISOString(),
    updatedAt: new Date('2025-04-09').toISOString(),
    _count: { votes: 112, perks: 0 },
    logoColor: '#84CC16',
  },
  {
    id: 'fb-13',
    name: 'CodePilot',
    slug: 'codepilot',
    tagline: 'AI pair programmer that writes, tests, and deploys with you',
    description: 'CodePilot understands your entire codebase architecture and can write complete features, generate tests, create documentation, and handle deployment.',
    logo: null,
    website: 'https://codepilot.dev',
    twitter: 'codepilot',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'United States',
    email: null,
    upvotes: 108,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-04-08').toISOString(),
    _count: { votes: 108, perks: 0 },
    logoColor: '#3B82F6',
  },
  {
    id: 'fb-14',
    name: 'MarketMind',
    slug: 'marketmind',
    tagline: 'AI content marketing platform that generates and optimizes campaigns',
    description: 'MarketMind analyzes your audience, competitors, and industry trends to create data-driven content strategies across every channel.',
    logo: null,
    website: 'https://marketmind.ai',
    twitter: 'marketmind_ai',
    linkedin: null,
    category: 'Marketing',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Brazil',
    email: null,
    upvotes: 95,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-25').toISOString(),
    updatedAt: new Date('2025-04-07').toISOString(),
    _count: { votes: 95, perks: 0 },
    logoColor: '#EC4899',
  },
  {
    id: 'fb-15',
    name: 'PropTech One',
    slug: 'proptech-one',
    tagline: 'Digital platform for fractional real estate investment globally',
    description: 'PropTech One democratizes real estate investing by allowing anyone to invest in premium properties worldwide with as little as $100.',
    logo: null,
    website: 'https://proptechone.com',
    twitter: 'proptech_one',
    linkedin: null,
    category: 'Finance',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'UAE',
    email: null,
    upvotes: 87,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-05').toISOString(),
    updatedAt: new Date('2025-04-06').toISOString(),
    _count: { votes: 87, perks: 0 },
    logoColor: '#D97706',
  },
  {
    id: 'fb-16',
    name: 'GameForge AI',
    slug: 'gameforge-ai',
    tagline: 'AI platform that generates game assets, levels, and entire games',
    description: 'GameForge AI empowers game developers with tools to generate 2D/3D assets, design levels, write narratives, and prototype game concepts.',
    logo: null,
    website: 'https://gameforge.ai',
    twitter: 'gameforge',
    linkedin: null,
    category: 'AI',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Japan',
    email: null,
    upvotes: 82,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-30').toISOString(),
    updatedAt: new Date('2025-04-05').toISOString(),
    _count: { votes: 82, perks: 0 },
    logoColor: '#A855F7',
  },
  {
    id: 'fb-17',
    name: 'TaskFlow',
    slug: 'taskflow',
    tagline: 'AI-powered project management that plans and executes automatically',
    description: 'TaskFlow reinvents project management with AI at its core. Describe your goal and let AI break it down, assign tasks, and adjust timelines dynamically.',
    logo: null,
    website: 'https://taskflow.app',
    twitter: 'taskflow',
    linkedin: null,
    category: 'Productivity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'South Korea',
    email: null,
    upvotes: 76,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-01').toISOString(),
    updatedAt: new Date('2025-04-04').toISOString(),
    _count: { votes: 76, perks: 0 },
    logoColor: '#06B6D4',
  },
  {
    id: 'fb-18',
    name: 'ShipFast',
    slug: 'shipfast',
    tagline: 'Autonomous logistics platform for D2C brands',
    description: 'ShipFast provides end-to-end logistics solutions for D2C brands, from warehousing to same-day delivery, reducing shipping costs by 35%.',
    logo: null,
    website: 'https://shipfast.co',
    twitter: 'shipfast',
    linkedin: null,
    category: 'Business',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 71,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-05').toISOString(),
    updatedAt: new Date('2025-04-03').toISOString(),
    _count: { votes: 71, perks: 0 },
    logoColor: '#F43F5E',
  },
  {
    id: 'fb-19',
    name: 'DataWeave',
    slug: 'dataweave',
    tagline: 'No-code ETL pipeline builder for modern data teams',
    description: 'DataWeave lets you build complex data pipelines with a visual drag-and-drop interface. Connect 200+ data sources, transform data, and automate workflows.',
    logo: null,
    website: 'https://dataweave.io',
    twitter: 'dataweave_io',
    linkedin: 'dataweave',
    category: 'Developer Tools',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: 'team@dataweave.io',
    upvotes: 167,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-30').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 167, perks: 2 },
    logoColor: '#2563EB',
  },
  {
    id: 'fb-20',
    name: 'SpendIQ',
    slug: 'spendiq',
    tagline: 'AI financial advisor for personal budgeting and investing',
    description: 'SpendIQ analyzes your spending patterns, optimizes your budget, and suggests investment strategies tailored to your financial goals.',
    logo: null,
    website: 'https://spendiq.com',
    twitter: 'spendiq',
    linkedin: null,
    category: 'Finance',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Canada',
    email: null,
    upvotes: 94,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-08').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 94, perks: 0 },
    logoColor: '#059669',
  },
  {
    id: 'fb-21',
    name: 'NotionAI Pro',
    slug: 'notionai-pro',
    tagline: 'Supercharge Notion with AI writing, summarizing, and automation',
    description: 'NotionAI Pro adds advanced AI capabilities to your Notion workspace: auto-generate content, summarize long docs, extract action items, and automate workflows.',
    logo: null,
    website: 'https://notionaipro.com',
    twitter: 'notionaipro',
    linkedin: 'notionai-pro',
    category: 'Productivity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 203,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-01').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 203, perks: 1 },
    logoColor: '#000000',
  },
  {
    id: 'fb-22',
    name: 'BrandPulse',
    slug: 'brandpulse',
    tagline: 'Real-time brand monitoring and social media analytics',
    description: 'BrandPulse tracks your brand mentions across 100+ platforms, analyzes sentiment, identifies trends, and provides actionable insights to grow your brand.',
    logo: null,
    website: 'https://brandpulse.ai',
    twitter: 'brandpulse_ai',
    linkedin: null,
    category: 'Marketing',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 134,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-18').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 134, perks: 0 },
    logoColor: '#E11D48',
  },
  {
    id: 'fb-23',
    name: 'LegalBot',
    slug: 'legalbot',
    tagline: 'AI-powered legal document analysis and contract review',
    description: 'LegalBot uses NLP and machine learning to review contracts, identify risks, suggest improvements, and generate legal documents in minutes.',
    logo: null,
    website: 'https://legalbot.ai',
    twitter: 'legalbot_ai',
    linkedin: null,
    category: 'AI',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United Kingdom',
    email: null,
    upvotes: 89,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-12').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 89, perks: 0 },
    logoColor: '#7C3AED',
  },
  {
    id: 'fb-24',
    name: 'RemoteFirst',
    slug: 'remotefirst',
    tagline: 'All-in-one remote work platform with async collaboration',
    description: 'RemoteFirst combines video, chat, project management, and async collaboration tools into one seamless platform built for distributed teams.',
    logo: null,
    website: 'https://remotefirst.co',
    twitter: 'remotefirst_co',
    linkedin: 'remotefirst',
    category: 'Productivity',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Germany',
    email: null,
    upvotes: 147,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-18').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 147, perks: 1 },
    logoColor: '#0284C7',
  },
  {
    id: 'fb-25',
    name: 'PitchGenius',
    slug: 'pitchgenius',
    tagline: 'AI pitch deck generator that tells your startup story',
    description: 'PitchGenius creates investor-ready pitch decks in minutes. Input your startup details and get beautiful, data-driven presentations that tell your story.',
    logo: null,
    website: 'https://pitchgenius.io',
    twitter: 'pitchgenius',
    linkedin: null,
    category: 'SaaS',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'United States',
    email: null,
    upvotes: 118,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-22').toISOString(),
    updatedAt: new Date('2025-04-09').toISOString(),
    _count: { votes: 118, perks: 0 },
    logoColor: '#DB2777',
  },
  {
    id: 'fb-26',
    name: 'APIForge',
    slug: 'apiforge',
    tagline: 'Visual API builder and testing platform for developers',
    description: 'APIForge provides a visual interface for designing, building, testing, and documenting APIs. Generate SDKs, mock servers, and API documentation automatically.',
    logo: null,
    website: 'https://apiforge.dev',
    twitter: 'apiforge',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'India',
    email: null,
    upvotes: 99,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-04-08').toISOString(),
    _count: { votes: 99, perks: 0 },
    logoColor: '#EA580C',
  },
  {
    id: 'fb-27',
    name: 'ClimaSense',
    slug: 'climasense',
    tagline: 'AI weather intelligence for agriculture and supply chains',
    description: 'ClimaSense provides hyper-local weather predictions and climate analytics to help farmers optimize yields and supply chains avoid disruptions.',
    logo: null,
    website: 'https://climasense.io',
    twitter: 'climasense',
    linkedin: null,
    category: 'AI',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Brazil',
    email: null,
    upvotes: 78,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-12').toISOString(),
    updatedAt: new Date('2025-04-06').toISOString(),
    _count: { votes: 78, perks: 0 },
    logoColor: '#16A34A',
  },
  {
    id: 'fb-28',
    name: 'RevSec',
    slug: 'revsec',
    tagline: 'Automated security compliance for startups and SMBs',
    description: 'RevSec automates SOC 2, GDPR, and HIPAA compliance with continuous monitoring, automated evidence collection, and one-click audit reports.',
    logo: null,
    website: 'https://revsec.io',
    twitter: 'revsec_io',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'United States',
    email: null,
    upvotes: 86,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-28').toISOString(),
    updatedAt: new Date('2025-04-05').toISOString(),
    _count: { votes: 86, perks: 0 },
    logoColor: '#B91C1C',
  },
  {
    id: 'fb-29',
    name: 'GrowthPilot',
    slug: 'growthpilot',
    tagline: 'Growth engine with automated A/B testing and analytics',
    description: 'GrowthPilot automates your growth experiments: set goals, define hypotheses, run A/B tests, and get AI-powered recommendations to boost conversion.',
    logo: null,
    website: 'https://growthpilot.io',
    twitter: 'growthpilot',
    linkedin: 'growthpilot',
    category: 'Marketing',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 105,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-22').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 105, perks: 1 },
    logoColor: '#7C3AED',
  },
  {
    id: 'fb-30',
    name: 'FormStack AI',
    slug: 'formstack-ai',
    tagline: 'Smart form builder with AI-powered data extraction',
    description: 'FormStack AI creates beautiful forms and uses AI to extract, categorize, and route form submissions automatically. No more manual data entry.',
    logo: null,
    website: 'https://formstackai.com',
    twitter: 'formstackai',
    linkedin: null,
    category: 'SaaS',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Australia',
    email: null,
    upvotes: 73,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-02').toISOString(),
    updatedAt: new Date('2025-04-04').toISOString(),
    _count: { votes: 73, perks: 0 },
    logoColor: '#0891B2',
  },
  {
    id: 'fb-31',
    name: 'TrustVault',
    slug: 'trustvault',
    tagline: 'Decentralized identity verification and KYC platform',
    description: 'TrustVault provides privacy-preserving identity verification using zero-knowledge proofs. Compliant with global regulations while protecting user privacy.',
    logo: null,
    website: 'https://trustvault.id',
    twitter: 'trustvault_id',
    linkedin: null,
    category: 'Finance',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Switzerland',
    email: null,
    upvotes: 91,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-22').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 91, perks: 0 },
    logoColor: '#1D4ED8',
  },
  {
    id: 'fb-32',
    name: 'SpaceWrite',
    slug: 'spacewrite',
    tagline: 'Collaborative writing workspace with AI editing tools',
    description: 'SpaceWrite is a distraction-free writing environment with real-time collaboration, AI grammar/style suggestions, version control, and publishing to multiple platforms.',
    logo: null,
    website: 'https://spacewrite.app',
    twitter: 'spacewrite',
    linkedin: null,
    category: 'Productivity',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Netherlands',
    email: null,
    upvotes: 68,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-08').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 68, perks: 0 },
    logoColor: '#9333EA',
  },
  {
    id: 'fb-33',
    name: 'AdIntelli',
    slug: 'adintelli',
    tagline: 'AI ad optimization platform for performance marketers',
    description: 'AdIntelli uses machine learning to optimize ad creatives, targeting, and bidding across Google, Meta, and TikTok. ROI-focused automation for growth teams.',
    logo: null,
    website: 'https://adintelli.ai',
    twitter: 'adintelli',
    linkedin: null,
    category: 'Marketing',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 83,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-18').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 83, perks: 0 },
    logoColor: '#E11D48',
  },
  {
    id: 'fb-34',
    name: 'BizMetrics',
    slug: 'bizmetrics',
    tagline: 'Executive dashboard that connects all your SaaS tools',
    description: 'BizMetrics creates a unified view of your business by connecting 50+ SaaS tools. Track revenue, MRR, churn, CAC, and LTV in one real-time dashboard.',
    logo: null,
    website: 'https://bizmetrics.io',
    twitter: 'bizmetrics',
    linkedin: 'bizmetrics',
    category: 'SaaS',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Ireland',
    email: null,
    upvotes: 156,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-08').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 156, perks: 2 },
    logoColor: '#0369A1',
  },
  {
    id: 'fb-35',
    name: 'SocialProof',
    slug: 'socialproof',
    tagline: 'Collect and showcase customer testimonials automatically',
    description: 'SocialProof automates testimonial collection via email, in-app widgets, and video requests. Display beautiful social proof widgets on your site to boost conversions.',
    logo: null,
    website: 'https://socialproof.io',
    twitter: 'socialproof',
    linkedin: null,
    category: 'Marketing',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Canada',
    email: null,
    upvotes: 64,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-10').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 64, perks: 0 },
    logoColor: '#CA8A04',
  },
  {
    id: 'fb-36',
    name: 'OpenHire',
    slug: 'openhire',
    tagline: 'Transparent salary and culture-first job board for startups',
    description: 'OpenHire is a job board where companies post transparent salary ranges, equity info, and culture details. No more guessing what a job really pays.',
    logo: null,
    website: 'https://openhire.co',
    twitter: 'openhire_co',
    linkedin: 'openhire',
    category: 'Business',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 57,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-12').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 57, perks: 0 },
    logoColor: '#15803D',
  },
]

export const fallbackWeeklyWinners = [
  { rank: 1, medal: 'gold', points: 340, ...fallbackStartups[0] },
  { rank: 2, medal: 'silver', points: 290, ...fallbackStartups[1] },
  { rank: 3, medal: 'bronze', points: 210, ...fallbackStartups[2] },
]

export const fallbackPerks: Record<string, { id: string; title: string; description: string; discount: string | null; url: string }[]> = {
  'neuralforge': [
    { id: 'fp-1', title: 'Free Trial', description: 'Get 3 months free on any plan', discount: '100% off for 3 months', url: '#' },
    { id: 'fp-2', title: 'Startup Discount', description: '50% off for early-stage startups', discount: '50% off first year', url: '#' },
  ],
  'paystream': [
    { id: 'fp-3', title: 'No Fees', description: 'Zero transaction fees for first $10K', discount: '$0 fees', url: '#' },
  ],
  'cloudnest': [
    { id: 'fp-4', title: 'Beta Access', description: 'Free beta access for Revolaunch community', discount: 'Free during beta', url: '#' },
  ],
  'mediscan-ai': [
    { id: 'fp-5', title: 'Demo License', description: 'Free 6-month demo license', discount: '6 months free', url: '#' },
  ],
  'dataweave': [
    { id: 'fp-6', title: 'Starter Plan', description: 'Free starter plan with 10K records/month', discount: 'Free tier', url: '#' },
    { id: 'fp-7', title: 'Community Discount', description: '30% off Pro plan for Revolaunch members', discount: '30% off', url: '#' },
  ],
  'notionai-pro': [
    { id: 'fp-8', title: 'Free Month', description: 'Get your first month free on any paid plan', discount: '1 month free', url: '#' },
  ],
  'remotefirst': [
    { id: 'fp-9', title: 'Team Discount', description: '20% off annual plans for teams under 25', discount: '20% off annual', url: '#' },
  ],
  'growthpilot': [
    { id: 'fp-10', title: 'Growth Pack', description: 'Free growth audit for Revolaunch startups', discount: 'Free audit', url: '#' },
  ],
  'bizmetrics': [
    { id: 'fp-11', title: 'Scale Plan', description: '3 months free on the Scale plan', discount: '3 months free', url: '#' },
    { id: 'fp-12', title: 'Integration Help', description: 'Free setup assistance for 5 SaaS integrations', discount: 'Free setup', url: '#' },
  ],
}

export const fallbackCategories = [
  { name: 'AI', count: 6, icon: '🤖' },
  { name: 'Finance', count: 5, icon: '💰' },
  { name: 'SaaS', count: 4, icon: '☁️' },
  { name: 'Developer Tools', count: 5, icon: '🛠️' },
  { name: 'Productivity', count: 4, icon: '⚡' },
  { name: 'Marketing', count: 4, icon: '📣' },
  { name: 'Business', count: 5, icon: '🏢' },
  { name: 'Cybersecurity', count: 1, icon: '🔒' },
]

export const fallbackStats = {
  totalStartups: 36,
  totalVotes: 4827,
  totalCategories: 8,
  featuredCount: 4,
  topCategories: [
    { name: 'AI', count: 6 },
    { name: 'Developer Tools', count: 5 },
    { name: 'Business', count: 5 },
    { name: 'Finance', count: 5 },
    { name: 'SaaS', count: 4 },
  ],
  stages: [
    { name: 'Seed', count: 12 },
    { name: 'Series A', count: 10 },
    { name: 'Pre-seed', count: 10 },
    { name: 'Series B', count: 3 },
    { name: 'Growth', count: 0 },
  ],
  countries: [
    { name: 'United States', count: 15 },
    { name: 'United Kingdom', count: 2 },
    { name: 'Canada', count: 3 },
    { name: 'Germany', count: 2 },
    { name: 'India', count: 2 },
    { name: 'France', count: 1 },
    { name: 'Australia', count: 2 },
    { name: 'Other', count: 9 },
  ],
  weeklyGrowth: [
    { week: 'Week 1', startups: 4 },
    { week: 'Week 2', startups: 7 },
    { week: 'Week 3', startups: 11 },
    { week: 'Week 4', startups: 18 },
    { week: 'Week 5', startups: 24 },
    { week: 'Week 6', startups: 30 },
    { week: 'Week 7', startups: 36 },
  ],
}

export interface CommunityBoard {
  id: string
  name: string
  description: string
  icon: string
  itemCount: number
  color: string
  items: CommunityBoardItem[]
}

export interface CommunityBoardItem {
  id: string
  title: string
  description: string
  author: string
  authorAvatar?: string
  createdAt: string
  upvotes: number
  tags: string[]
  startup?: string
  mrr?: number
  link?: string
}

export const fallbackCommunityBoards: CommunityBoard[] = [
  {
    id: 'mrr-board',
    name: 'MRR Board',
    description: 'Share your monthly recurring revenue milestones',
    icon: '📊',
    itemCount: 42,
    color: '#22C55E',
    items: [
      {
        id: 'mrr-1',
        title: '$50K MRR - NeuralForge hits milestone!',
        description: 'We just crossed $50K MRR after 8 months. AI code review is resonating with dev teams.',
        author: 'Alex Chen',
        createdAt: '2025-04-18T10:30:00Z',
        upvotes: 87,
        tags: ['AI', 'SaaS', 'Milestone'],
        startup: 'NeuralForge',
        mrr: 50000,
      },
      {
        id: 'mrr-2',
        title: 'PayStream reaches $120K MRR',
        description: 'Cross-border payments are exploding. We added 200 new SMBs this month alone.',
        author: 'Sarah Kim',
        createdAt: '2025-04-17T14:00:00Z',
        upvotes: 134,
        tags: ['FinTech', 'MRR'],
        startup: 'PayStream',
        mrr: 120000,
      },
      {
        id: 'mrr-3',
        title: 'BizMetrics at $75K MRR',
        description: 'Connecting all SaaS tools into one dashboard was the right bet. 500+ companies using us now.',
        author: 'Mike Torres',
        createdAt: '2025-04-16T09:15:00Z',
        upvotes: 65,
        tags: ['SaaS', 'Analytics'],
        startup: 'BizMetrics',
        mrr: 75000,
      },
      {
        id: 'mrr-4',
        title: 'NotionAI Pro hit $30K MRR in 3 months',
        description: 'The Notion community is incredible. Word of mouth drove 80% of our growth.',
        author: 'Lisa Wang',
        createdAt: '2025-04-15T16:45:00Z',
        upvotes: 92,
        tags: ['Productivity', 'MRR'],
        startup: 'NotionAI Pro',
        mrr: 30000,
      },
    ],
  },
  {
    id: 'weekly-board',
    name: 'Weekly Board',
    description: 'Track your weekly progress and compete for top rankings',
    icon: '🏆',
    itemCount: 1420,
    color: '#F59E0B',
    items: [
      {
        id: 'wb-1',
        title: 'NeuralForge - 340 pts this week',
        description: 'New features shipped: GitHub integration, multi-language support, and CI/CD pipeline hooks.',
        author: 'Alex Chen',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 340,
        tags: ['Weekly Winner'],
        startup: 'NeuralForge',
      },
      {
        id: 'wb-2',
        title: 'PayStream - 290 pts this week',
        description: 'Launched in 5 new markets and partnered with 3 banks for instant settlement.',
        author: 'Sarah Kim',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 290,
        tags: ['Weekly Runner-up'],
        startup: 'PayStream',
      },
      {
        id: 'wb-3',
        title: 'CloudNest - 210 pts this week',
        description: 'Visual infrastructure designer went viral on Twitter. 5K signups in one day!',
        author: 'Max Braun',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 210,
        tags: ['Weekly 3rd Place'],
        startup: 'CloudNest',
      },
    ],
  },
  {
    id: 'raising-capital',
    name: 'Raising Capital',
    description: 'Connect with investors and showcase your fundraising journey',
    icon: '💰',
    itemCount: 89,
    color: '#3B82F6',
    items: [
      {
        id: 'rc-1',
        title: 'Series A round - CloudNest raising $5M',
        description: 'Building the future of visual infrastructure management. Looking for strategic partners.',
        author: 'Max Braun',
        createdAt: '2025-04-18T08:00:00Z',
        upvotes: 156,
        tags: ['Series A', 'DevTools'],
        startup: 'CloudNest',
        link: '#',
      },
      {
        id: 'rc-2',
        title: 'Seed round - GrowthPilot raising $2M',
        description: 'AI-powered growth engine. Already helping 200+ companies run better A/B tests.',
        author: 'Jordan Lee',
        createdAt: '2025-04-17T11:30:00Z',
        upvotes: 89,
        tags: ['Seed', 'Marketing'],
        startup: 'GrowthPilot',
        link: '#',
      },
    ],
  },
  {
    id: 'job-board',
    name: 'Job Board',
    description: 'Find and post jobs at the most innovative startups',
    icon: '💼',
    itemCount: 0,
    color: '#8B5CF6',
    items: [],
  },
  {
    id: 'open-to-acquisition',
    name: 'Open to Acquisition',
    description: 'Startups open to being acquired',
    icon: '🤝',
    itemCount: 12,
    color: '#EC4899',
    items: [
      {
        id: 'oa-1',
        title: 'GameForge AI exploring acquisition options',
        description: 'Profitable AI game asset platform. 15K users, $8K MRR. Looking for strategic acquirers.',
        author: 'Yuki Tanaka',
        createdAt: '2025-04-15T10:00:00Z',
        upvotes: 45,
        tags: ['AI', 'Gaming'],
        startup: 'GameForge AI',
      },
      {
        id: 'oa-2',
        title: 'SocialProof open to acquisition',
        description: 'Growing testimonial platform with 3K customers. Strong retention and NPS score.',
        author: 'Emma Davis',
        createdAt: '2025-04-14T14:30:00Z',
        upvotes: 32,
        tags: ['SaaS', 'Marketing'],
        startup: 'SocialProof',
      },
    ],
  },
  {
    id: 'perks-directory',
    name: 'Perks Directory',
    description: 'Exclusive deals and perks for the startup community',
    icon: '🎁',
    itemCount: 12,
    color: '#F97316',
    items: [
      {
        id: 'pd-1',
        title: 'NeuralForge - 3 months free',
        description: 'Get 3 months free on any NeuralForge plan. Perfect for dev teams shipping fast.',
        author: 'NeuralForge',
        createdAt: '2025-04-10T00:00:00Z',
        upvotes: 234,
        tags: ['AI', 'DevTools', 'Free Trial'],
        startup: 'NeuralForge',
      },
      {
        id: 'pd-2',
        title: 'PayStream - Zero fees on first $10K',
        description: 'Start accepting international payments with zero transaction fees on your first $10K.',
        author: 'PayStream',
        createdAt: '2025-04-08T00:00:00Z',
        upvotes: 178,
        tags: ['FinTech', 'Free Trial'],
        startup: 'PayStream',
      },
      {
        id: 'pd-3',
        title: 'BizMetrics - 3 months free Scale plan',
        description: 'Unify all your SaaS metrics in one dashboard. 3 months free on the Scale plan.',
        author: 'BizMetrics',
        createdAt: '2025-04-05T00:00:00Z',
        upvotes: 145,
        tags: ['SaaS', 'Analytics', 'Free Trial'],
        startup: 'BizMetrics',
      },
    ],
  },
]

export const categoryColors: Record<string, string> = {
  'AI': 'bg-purple-500/20 text-purple-300 border border-purple-500/30',
  'Finance': 'bg-green-500/20 text-green-300 border border-green-500/30',
  'Productivity': 'bg-sky-500/20 text-sky-300 border border-sky-500/30',
  'Marketing': 'bg-pink-500/20 text-pink-300 border border-pink-500/30',
  'Business': 'bg-amber-500/20 text-amber-300 border border-amber-500/30',
  'Developer Tools': 'bg-blue-500/20 text-blue-300 border border-blue-500/30',
  'SaaS': 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30',
  'Cybersecurity': 'bg-red-500/20 text-red-300 border border-red-500/30',
}

export const categoryIcons: Record<string, string> = {
  'AI': '🤖',
  'Finance': '💰',
  'Productivity': '⚡',
  'Marketing': '📣',
  'Business': '🏢',
  'Developer Tools': '🛠️',
  'SaaS': '☁️',
  'Cybersecurity': '🔒',
}

export function getCategoryColor(cat: string) {
  return categoryColors[cat] || 'bg-gray-500/20 text-gray-300 border border-gray-500/30'
}

export function getCategoryIcon(cat: string) {
  return categoryIcons[cat] || '💡'
}

export function getStageColor(stage: string) {
  switch (stage) {
    case 'Pre-seed': return 'bg-gray-500/20 text-gray-300 border border-gray-500/30'
    case 'Seed': return 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
    case 'Series A': return 'bg-blue-500/20 text-blue-300 border border-blue-500/30'
    case 'Series B': return 'bg-violet-500/20 text-violet-300 border border-violet-500/30'
    case 'Growth': return 'bg-orange-500/20 text-orange-300 border border-orange-500/30'
    default: return 'bg-gray-500/20 text-gray-300 border border-gray-500/30'
  }
}
