// Static fallback data used when database is not available (e.g., Vercel serverless)
export const fallbackStartups = [
  {
    id: 'fb-1',
    name: 'NeuralForge',
    slug: 'neuralforge',
    tagline: 'AI-powered code review that catches bugs before they ship',
    description: 'NeuralForge uses advanced machine learning models to analyze your codebase in real-time, identifying potential bugs, security vulnerabilities, and performance issues. Compatible with all major IDEs and CI/CD pipelines.',
    logo: null,
    website: 'https://neuralforge.dev',
    twitter: 'neuralforge',
    linkedin: null,
    category: 'AI / Machine Learning',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 342,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 342, perks: 2 },
  },
  {
    id: 'fb-2',
    name: 'PayStream',
    slug: 'paystream',
    tagline: 'Instant cross-border payments for freelancers and SMBs',
    description: 'PayStream eliminates the pain of international payments. Send and receive money in 50+ currencies with zero fees, instant settlement, and transparent exchange rates.',
    logo: null,
    website: 'https://paystream.io',
    twitter: 'paystream',
    linkedin: null,
    category: 'FinTech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United Kingdom',
    email: null,
    upvotes: 287,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-02-10').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 287, perks: 1 },
  },
  {
    id: 'fb-3',
    name: 'CloudNest',
    slug: 'cloudnest',
    tagline: 'Deploy infrastructure as code with visual drag-and-drop',
    description: 'CloudNest makes infrastructure management accessible to everyone. Visually design your cloud architecture and get optimized, production-ready infrastructure code.',
    logo: null,
    website: 'https://cloudnest.dev',
    twitter: 'cloudnest',
    linkedin: null,
    category: 'DevTools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Germany',
    email: null,
    upvotes: 256,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 256, perks: 1 },
  },
  {
    id: 'fb-4',
    name: 'MediScan AI',
    slug: 'mediscan-ai',
    tagline: 'AI diagnostic assistant for radiologists and clinicians',
    description: 'MediScan AI accelerates medical imaging diagnostics with FDA-cleared algorithms trained on millions of medical images, detecting anomalies with 97.3% accuracy.',
    logo: null,
    website: 'https://mediscan.ai',
    twitter: 'mediscan_ai',
    linkedin: null,
    category: 'HealthTech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Israel',
    email: null,
    upvotes: 234,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 234, perks: 1 },
  },
  {
    id: 'fb-5',
    name: 'LearnLoop',
    slug: 'learnloop',
    tagline: 'Personalized AI tutoring that adapts to every learning style',
    description: 'LearnLoop creates personalized curricula that adapt in real-time based on learning patterns, strengths, and weaknesses. Delivering 1-on-1 tutoring at scale.',
    logo: null,
    website: 'https://learnloop.ai',
    twitter: 'learnloop',
    linkedin: null,
    category: 'EdTech',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Canada',
    email: null,
    upvotes: 198,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-15').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 198, perks: 0 },
  },
  {
    id: 'fb-6',
    name: 'GreenGrid',
    slug: 'greengrid',
    tagline: 'Smart energy management platform for commercial buildings',
    description: 'GreenGrid helps commercial property owners reduce energy costs by up to 40% through AI-optimized energy management with IoT sensors and ML algorithms.',
    logo: null,
    website: 'https://greengrid.energy',
    twitter: 'greengrid_energy',
    linkedin: null,
    category: 'Climate Tech',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'Netherlands',
    email: null,
    upvotes: 176,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-25').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 176, perks: 0 },
  },
  {
    id: 'fb-7',
    name: 'StackBot',
    slug: 'stackbot',
    tagline: 'AI customer support agent trained on your entire documentation',
    description: 'StackBot creates intelligent customer support agents by ingesting your docs, APIs, and knowledge base to provide accurate, contextual answers 24/7.',
    logo: null,
    website: 'https://stackbot.io',
    twitter: 'stackbot',
    linkedin: null,
    category: 'SaaS',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Australia',
    email: null,
    upvotes: 163,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-20').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 163, perks: 0 },
  },
  {
    id: 'fb-8',
    name: 'ChainVault',
    slug: 'chainvault',
    tagline: 'Institutional-grade DeFi custody and treasury management',
    description: 'ChainVault bridges traditional finance and DeFi with institutional custody, multi-sig security, insurance coverage, and regulatory compliance.',
    logo: null,
    website: 'https://chainvault.finance',
    twitter: 'chainvault_fi',
    linkedin: null,
    category: 'Web3 / Blockchain',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Singapore',
    email: null,
    upvotes: 152,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 152, perks: 0 },
  },
  {
    id: 'fb-9',
    name: 'FlowMetrics',
    slug: 'flowmetrics',
    tagline: 'Real-time product analytics with built-in AI insights',
    description: 'FlowMetrics gives product teams AI-driven analytics that go beyond dashboards. Discover behavior patterns, predict churn, and identify growth opportunities.',
    logo: null,
    website: 'https://flowmetrics.com',
    twitter: 'flowmetrics',
    linkedin: null,
    category: 'SaaS',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'France',
    email: null,
    upvotes: 141,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-10').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 141, perks: 0 },
  },
  {
    id: 'fb-10',
    name: 'HireLogic',
    slug: 'hirelogic',
    tagline: 'AI-powered hiring that eliminates bias and accelerates recruitment',
    description: 'HireLogic transforms hiring with intelligent job descriptions, automated sourcing, bias-free screening, and structured interview guides.',
    logo: null,
    website: 'https://hirelogic.com',
    twitter: 'hirelogic',
    linkedin: null,
    category: 'HR / Recruiting',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 128,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-15').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 128, perks: 0 },
  },
  {
    id: 'fb-11',
    name: 'CyberShield AI',
    slug: 'cybershield-ai',
    tagline: 'Autonomous threat detection and response for SMBs',
    description: 'CyberShield AI provides enterprise-grade cybersecurity for SMBs with autonomous AI agents that monitor your infrastructure 24/7.',
    logo: null,
    website: 'https://cybershield.ai',
    twitter: 'cybershield_ai',
    linkedin: null,
    category: 'Cybersecurity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Estonia',
    email: null,
    upvotes: 119,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-20').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 119, perks: 0 },
  },
  {
    id: 'fb-12',
    name: 'FreshCart',
    slug: 'freshcart',
    tagline: 'AI-driven grocery delivery with real-time inventory tracking',
    description: 'FreshCart connects consumers directly with local grocery stores. AI optimizes delivery routes, predicts demand, and ensures fresh products arrive within 30 minutes.',
    logo: null,
    website: 'https://freshcart.app',
    twitter: 'freshcart',
    linkedin: null,
    category: 'E-Commerce',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'India',
    email: null,
    upvotes: 112,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-25').toISOString(),
    updatedAt: new Date('2025-04-09').toISOString(),
    _count: { votes: 112, perks: 0 },
  },
  {
    id: 'fb-13',
    name: 'CodePilot',
    slug: 'codepilot',
    tagline: 'AI pair programmer that writes, tests, and deploys with you',
    description: 'CodePilot understands your entire codebase architecture and can write complete features, generate tests, create documentation, and handle deployment.',
    logo: null,
    website: 'https://codepilot.dev',
    twitter: 'codepilot',
    linkedin: null,
    category: 'DevTools',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'United States',
    email: null,
    upvotes: 108,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-04-08').toISOString(),
    _count: { votes: 108, perks: 0 },
  },
  {
    id: 'fb-14',
    name: 'MarketMind',
    slug: 'marketmind',
    tagline: 'AI content marketing platform that generates and optimizes campaigns',
    description: 'MarketMind analyzes your audience, competitors, and industry trends to create data-driven content strategies across every channel.',
    logo: null,
    website: 'https://marketmind.ai',
    twitter: 'marketmind_ai',
    linkedin: null,
    category: 'Marketing',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Brazil',
    email: null,
    upvotes: 95,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-25').toISOString(),
    updatedAt: new Date('2025-04-07').toISOString(),
    _count: { votes: 95, perks: 0 },
  },
  {
    id: 'fb-15',
    name: 'PropTech One',
    slug: 'proptech-one',
    tagline: 'Digital platform for fractional real estate investment globally',
    description: 'PropTech One democratizes real estate investing by allowing anyone to invest in premium properties worldwide with as little as $100.',
    logo: null,
    website: 'https://proptechone.com',
    twitter: 'proptech_one',
    linkedin: null,
    category: 'Real Estate Tech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'UAE',
    email: null,
    upvotes: 87,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-05').toISOString(),
    updatedAt: new Date('2025-04-06').toISOString(),
    _count: { votes: 87, perks: 0 },
  },
  {
    id: 'fb-16',
    name: 'GameForge AI',
    slug: 'gameforge-ai',
    tagline: 'AI platform that generates game assets, levels, and entire games',
    description: 'GameForge AI empowers game developers with tools to generate 2D/3D assets, design levels, write narratives, and prototype game concepts.',
    logo: null,
    website: 'https://gameforge.ai',
    twitter: 'gameforge',
    linkedin: null,
    category: 'Gaming',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Japan',
    email: null,
    upvotes: 82,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-30').toISOString(),
    updatedAt: new Date('2025-04-05').toISOString(),
    _count: { votes: 82, perks: 0 },
  },
  {
    id: 'fb-17',
    name: 'TaskFlow',
    slug: 'taskflow',
    tagline: 'AI-powered project management that plans and executes automatically',
    description: 'TaskFlow reinvents project management with AI at its core. Describe your goal and let AI break it down, assign tasks, and adjust timelines dynamically.',
    logo: null,
    website: 'https://taskflow.app',
    twitter: 'taskflow',
    linkedin: null,
    category: 'Productivity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'South Korea',
    email: null,
    upvotes: 76,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-01').toISOString(),
    updatedAt: new Date('2025-04-04').toISOString(),
    _count: { votes: 76, perks: 0 },
  },
  {
    id: 'fb-18',
    name: 'ShipFast',
    slug: 'shipfast',
    tagline: 'Autonomous logistics platform for D2C brands',
    description: 'ShipFast provides end-to-end logistics solutions for D2C brands, from warehousing to same-day delivery, reducing shipping costs by 35%.',
    logo: null,
    website: 'https://shipfast.co',
    twitter: 'shipfast',
    linkedin: null,
    category: 'Logistics',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 71,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-05').toISOString(),
    updatedAt: new Date('2025-04-03').toISOString(),
    _count: { votes: 71, perks: 0 },
  },
]

export const fallbackPerks: Record<string, { id: string; title: string; description: string; discount: string | null; url: string }[]> = {
  'neuralforge': [
    { id: 'fp-1', title: 'Free Trial', description: 'Get 3 months free on any plan', discount: '100% off for 3 months', url: '#' },
    { id: 'fp-2', title: 'Startup Discount', description: '50% off for early-stage startups', discount: '50% off first year', url: '#' },
  ],
  'paystream': [
    { id: 'fp-3', title: 'No Fees', description: 'Zero transaction fees for first $10K', discount: '$0 fees', url: '#' },
  ],
  'cloudnest': [
    { id: 'fp-4', title: 'Beta Access', description: 'Free beta access for Revolaunch community', discount: 'Free during beta', url: '#' },
  ],
  'mediscan-ai': [
    { id: 'fp-5', title: 'Demo License', description: 'Free 6-month demo license', discount: '6 months free', url: '#' },
  ],
}

export const fallbackCategories = [
  { name: 'AI / Machine Learning', count: 1 },
  { name: 'SaaS', count: 2 },
  { name: 'FinTech', count: 1 },
  { name: 'HealthTech', count: 1 },
  { name: 'EdTech', count: 1 },
  { name: 'E-Commerce', count: 1 },
  { name: 'DevTools', count: 2 },
  { name: 'Cybersecurity', count: 1 },
  { name: 'Climate Tech', count: 1 },
  { name: 'Web3 / Blockchain', count: 1 },
  { name: 'Productivity', count: 1 },
  { name: 'HR / Recruiting', count: 1 },
  { name: 'Marketing', count: 1 },
  { name: 'Real Estate Tech', count: 1 },
  { name: 'Gaming', count: 1 },
  { name: 'Logistics', count: 1 },
]

export const fallbackStats = {
  totalStartups: 18,
  totalVotes: 2827,
  totalCategories: 16,
  featuredCount: 4,
  topCategories: [
    { name: 'SaaS', count: 2 },
    { name: 'DevTools', count: 2 },
    { name: 'AI / Machine Learning', count: 1 },
    { name: 'FinTech', count: 1 },
    { name: 'HealthTech', count: 1 },
  ],
  stages: [
    { name: 'Seed', count: 5 },
    { name: 'Series A', count: 5 },
    { name: 'Pre-seed', count: 4 },
    { name: 'Series B', count: 2 },
    { name: 'Growth', count: 0 },
  ],
}
