// Static fallback data used when database is not available (e.g., Vercel serverless)
// 36 real Product Hunt startups with verified data

export interface Startup {
  id: string
  name: string
  slug: string
  tagline: string
  description: string | null
  logo: string | null
  website: string
  twitter: string | null
  linkedin: string | null
  category: string
  stage: string
  teamSize: string
  foundedYear: number | null
  country: string | null
  email: string | null
  upvotes: number
  featured: boolean
  status: string
  createdAt: string
  updatedAt: string
  _count: { votes: number; perks: number }
  logoColor?: string
  weeklyPoints?: number
}

export const fallbackStartups: Startup[] = [
  {
    id: 'ph-1',
    name: 'MGX (Now Atoms)',
    slug: 'metagpt',
    tagline: 'The first AI dev team',
    description: 'MGX is a multi-agent AI platform based on real software SOPs. It simulates a complete software development team with product managers, architects, engineers, and QA agents working together to build software autonomously.',
    logo: 'https://logo.clearbit.com/atoms.dev',
    website: 'https://atoms.dev',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Series B',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'China',
    email: null,
    upvotes: 800,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 800, perks: 2 },
    logoColor: '#4F46E5',
    weeklyPoints: 800,
  },
  {
    id: 'ph-2',
    name: 'Sider 5.0',
    slug: 'sider-5',
    tagline: 'AI Research Agent & Extension',
    description: 'Sider 5.0 introduces Deep Research that mimics human research processes, scanning 100+ relevant sources and creating visualized reports. It also serves as a powerful browser extension for AI-assisted reading and writing.',
    logo: 'https://logo.clearbit.com/sider.ai',
    website: 'https://sider.ai',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'China',
    email: null,
    upvotes: 743,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-01-18').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 743, perks: 1 },
    logoColor: '#2563EB',
    weeklyPoints: 743,
  },
  {
    id: 'ph-3',
    name: 'Dreamina',
    slug: 'dreamina',
    tagline: 'All-in-one AI creative suite for all your artistic work',
    description: 'Dreamina is an AI platform by ByteDance for creating stunning posters, flyers, and logos. It leverages advanced generative AI to help designers and non-designers create professional visual content effortlessly.',
    logo: 'https://logo.clearbit.com/dreamina.capcut.com',
    website: 'https://dreamina.capcut.com',
    twitter: null,
    linkedin: null,
    category: 'Design',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2023,
    country: 'China',
    email: null,
    upvotes: 620,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-02-05').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 620, perks: 1 },
    logoColor: '#EC4899',
    weeklyPoints: 620,
  },
  {
    id: 'ph-4',
    name: 'PageOn.AI 2.0',
    slug: 'pageon-ai',
    tagline: 'Cursor for Visual Communication, beyond slides',
    description: 'PageOn.AI 2.0 provides AI agents that plan, research, and design dynamic, stunning pages. It goes beyond traditional slides to create interactive visual content for presentations, reports, and storytelling.',
    logo: 'https://logo.clearbit.com/pageon.ai',
    website: 'https://pageon.ai',
    twitter: null,
    linkedin: null,
    category: 'Design',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'China',
    email: null,
    upvotes: 415,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-02-15').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 415, perks: 1 },
    logoColor: '#7C3AED',
  },
  {
    id: 'ph-5',
    name: 'Mailgo',
    slug: 'mailgo',
    tagline: 'AI-powered cold email platform that boosts deliverability',
    description: 'Mailgo unifies an AI leads finding agent, smart scheduling, and pre-warmed accounts to maximize cold email deliverability. It helps sales teams reach more prospects with personalized outreach at scale.',
    logo: 'https://logo.clearbit.com/mailgo.ai',
    website: 'https://www.mailgo.ai',
    twitter: null,
    linkedin: null,
    category: 'Marketing',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 482,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-20').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 482, perks: 0 },
    logoColor: '#F97316',
  },
  {
    id: 'ph-6',
    name: 'EasySite AI',
    slug: 'easysite-ai',
    tagline: 'Build AI apps that ship revenue in seconds',
    description: 'EasySite AI lets you go from idea to launch in minutes. Build AI-powered applications with no code, connect revenue streams, and deploy production-ready apps without any technical expertise.',
    logo: 'https://logo.clearbit.com/easysite.ai',
    website: 'https://easysite.ai',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 415,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 415, perks: 0 },
    logoColor: '#10B981',
  },
  {
    id: 'ph-7',
    name: 'Jolt AI',
    slug: 'jolt-ai',
    tagline: 'AI assistant for 100k to multi-million line codebases',
    description: 'Jolt AI is an instant codebase expert for AI code generation and chat. It indexes massive codebases in seconds and provides accurate, context-aware code completions and explanations across millions of lines of code.',
    logo: 'https://logo.clearbit.com/joltai.com',
    website: 'https://joltai.com',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#F59E0B',
  },
  {
    id: 'ph-8',
    name: 'Kibo UI',
    slug: 'kibo-ui',
    tagline: 'Advanced, open-source components for shadcn/ui',
    description: 'Kibo UI offers a custom registry of composable, accessible, and open-source components built on top of shadcn/ui. It provides beautifully designed, production-ready UI building blocks for modern web applications.',
    logo: 'https://logo.clearbit.com/kibo-ui.com',
    website: 'https://www.kibo-ui.com',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 300,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-08').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 300, perks: 0 },
    logoColor: '#0EA5E9',
  },
  {
    id: 'ph-9',
    name: 'Lingo.dev',
    slug: 'lingo-dev',
    tagline: 'AI localization for teams who ship fast',
    description: 'Lingo.dev is an AI Localization Engine that turns weeks of translation work into automated pull requests. It integrates into your CI/CD pipeline to automatically translate, review, and deploy content changes across all your locales.',
    logo: 'https://logo.clearbit.com/lingo.dev',
    website: 'https://lingo.dev',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 280,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-10').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 280, perks: 0 },
    logoColor: '#8B5CF6',
  },
  {
    id: 'ph-10',
    name: 'Appwrite',
    slug: 'appwrite',
    tagline: "The developers' cloud",
    description: 'Appwrite is an open-source cloud development platform with built-in backend infrastructure. It provides auth, databases, functions, storage, and messaging out of the box, letting developers focus on building their apps.',
    logo: 'https://logo.clearbit.com/appwrite.io',
    website: 'https://appwrite.io',
    twitter: 'appwrite_io',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2019,
    country: 'Germany',
    email: null,
    upvotes: 250,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-12').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 250, perks: 0 },
    logoColor: '#FD366E',
  },
  {
    id: 'ph-11',
    name: 'next-forge',
    slug: 'next-forge',
    tagline: 'Full-stack framework with authentication, payments and more',
    description: 'next-forge is an opinionated Next.js boilerplate that comes pre-configured with authentication, payments, database, and more. It helps developers launch full-stack applications faster with production-ready architecture.',
    logo: 'https://logo.clearbit.com/middlefield.dev',
    website: 'https://forge.middlefield.dev',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 200,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-15').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 200, perks: 0 },
    logoColor: '#059669',
  },
  {
    id: 'ph-12',
    name: 'SpeakON',
    slug: 'speakon',
    tagline: 'A MagSafe AI device for a post-keyboard world',
    description: 'SpeakON is a hardware AI device that snaps onto your iPhone via MagSafe, enabling voice-first interactions. It aims to reduce screen time by letting you accomplish tasks through natural conversation instead of typing.',
    logo: 'https://logo.clearbit.com/getspeakon.com',
    website: 'https://getspeakon.com',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-18').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#1D4ED8',
  },
  {
    id: 'ph-13',
    name: 'LambdaTest',
    slug: 'lambdatest',
    tagline: 'Accessibility Testing Suite',
    description: 'LambdaTest Accessibility Testing Suite helps ensure web inclusivity and compliance with WCAG standards. It provides automated and manual accessibility testing tools to identify and fix issues across your web applications.',
    logo: 'https://logo.clearbit.com/lambdatest.com',
    website: 'https://www.lambdatest.com',
    twitter: 'lambdatesting',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2017,
    country: 'India',
    email: null,
    upvotes: 250,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-22').toISOString(),
    updatedAt: new Date('2025-04-09').toISOString(),
    _count: { votes: 250, perks: 0 },
    logoColor: '#DC2626',
  },
  {
    id: 'ph-14',
    name: 'Genspark',
    slug: 'genspark',
    tagline: 'AI Super Agent',
    description: 'Genspark is an AI-powered search and research agent that goes beyond traditional search engines. It autonomously researches topics, synthesizes information from multiple sources, and delivers comprehensive, accurate answers.',
    logo: 'https://logo.clearbit.com/genspark.ai',
    website: 'https://genspark.ai',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 220,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-20').toISOString(),
    updatedAt: new Date('2025-04-08').toISOString(),
    _count: { votes: 220, perks: 0 },
    logoColor: '#06B6D4',
  },
  {
    id: 'ph-15',
    name: 'AtlasVibe',
    slug: 'atlasvibe',
    tagline: 'Pricing in seconds',
    description: 'AtlasVibe is a SaaS pricing tool that helps startups determine optimal pricing for their products. It provides data-driven pricing recommendations and A/B testing capabilities to maximize revenue and conversion rates.',
    logo: 'https://logo.clearbit.com/atlasvibe.com',
    website: 'https://atlasvibe.com',
    twitter: null,
    linkedin: null,
    category: 'Business',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 180,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-22').toISOString(),
    updatedAt: new Date('2025-04-07').toISOString(),
    _count: { votes: 180, perks: 0 },
    logoColor: '#D97706',
  },
  {
    id: 'ph-16',
    name: 'Cursor',
    slug: 'cursor',
    tagline: 'The AI Code Editor',
    description: 'Cursor is an AI-first code editor built for pair programming with AI. It features intelligent code completion, natural language code editing, codebase-aware suggestions, and seamless integration with popular development workflows.',
    logo: 'https://logo.clearbit.com/cursor.com',
    website: 'https://cursor.com',
    twitter: 'cursor_ai',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2022,
    country: 'United States',
    email: null,
    upvotes: 795,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 795, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'ph-17',
    name: 'Bolt.new',
    slug: 'bolt-new',
    tagline: 'Prompt, run, edit, and deploy full-stack web apps',
    description: 'Bolt.new is an AI-powered full-stack web app builder that runs entirely in the browser. Simply describe your app idea in natural language and watch as it generates, runs, and deploys a complete web application in seconds.',
    logo: 'https://logo.clearbit.com/bolt.new',
    website: 'https://bolt.new',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 700,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-25').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 700, perks: 0 },
    logoColor: '#F97316',
  },
  {
    id: 'ph-18',
    name: 'Lovable',
    slug: 'lovable',
    tagline: 'Build software with AI',
    description: 'Lovable (formerly GPT Engineer) is an AI-powered software builder that creates full-stack applications from natural language prompts. It generates clean, maintainable code and handles the entire development lifecycle from design to deployment.',
    logo: 'https://logo.clearbit.com/lovable.dev',
    website: 'https://lovable.dev',
    twitter: 'lovable_dev',
    linkedin: null,
    category: 'AI',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 650,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-01').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 650, perks: 0 },
    logoColor: '#EC4899',
  },
  {
    id: 'ph-19',
    name: 'v0 by Vercel',
    slug: 'v0-by-vercel',
    tagline: 'Generative UI',
    description: 'v0 by Vercel is an AI tool that generates React UI components from text descriptions. It produces production-quality, accessible, and customizable UI code using shadcn/ui and Tailwind CSS, ready to integrate into your project.',
    logo: 'https://logo.clearbit.com/v0.dev',
    website: 'https://v0.dev',
    twitter: 'vercel',
    linkedin: null,
    category: 'AI',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2023,
    country: 'United States',
    email: null,
    upvotes: 500,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-10').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 500, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'ph-20',
    name: 'Replit Agent',
    slug: 'replit-agent',
    tagline: 'AI software development agent',
    description: 'Replit Agent is an AI agent that builds, deploys, and debugs software autonomously. It understands your requirements, generates code, handles dependencies, and manages the entire development process from concept to production.',
    logo: 'https://logo.clearbit.com/replit.com',
    website: 'https://replit.com',
    twitter: 'replit',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2016,
    country: 'United States',
    email: null,
    upvotes: 450,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-18').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 450, perks: 0 },
    logoColor: '#F26207',
  },
  {
    id: 'ph-21',
    name: 'ChatGPT Images 2.0',
    slug: 'chatgpt-images-2',
    tagline: 'First image model with thinking capabilities',
    description: 'OpenAI\'s ChatGPT Images 2.0 is the first image generation model with reasoning capabilities. It can understand complex prompts, reason about spatial relationships, and generate photorealistic images with unprecedented accuracy.',
    logo: 'https://logo.clearbit.com/openai.com',
    website: 'https://chat.openai.com',
    twitter: 'openai',
    linkedin: null,
    category: 'AI',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2024,
    country: 'United States',
    email: null,
    upvotes: 400,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-25').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 400, perks: 0 },
    logoColor: '#10A37F',
  },
  {
    id: 'ph-22',
    name: 'Midday',
    slug: 'midday',
    tagline: 'AI Workspace for Founders',
    description: 'Midday is an all-in-one AI workspace designed for startup founders. It consolidates tasks like document management, financial tracking, team coordination, and strategic planning into a single intelligent platform.',
    logo: 'https://logo.clearbit.com/midday.ai',
    website: 'https://midday.ai',
    twitter: null,
    linkedin: null,
    category: 'Productivity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2023,
    country: 'Denmark',
    email: null,
    upvotes: 300,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-25').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 300, perks: 0 },
    logoColor: '#6366F1',
  },
  {
    id: 'ph-23',
    name: 'Supabase',
    slug: 'supabase',
    tagline: 'The open source Firebase alternative',
    description: 'Supabase is an open source backend-as-a-service with PostgreSQL at its core. It provides authentication, real-time subscriptions, storage, and edge functions, giving developers a scalable and self-hostable alternative to Firebase.',
    logo: 'https://logo.clearbit.com/supabase.com',
    website: 'https://supabase.com',
    twitter: 'supabase',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Growth',
    teamSize: '51-200',
    foundedYear: 2020,
    country: 'Singapore',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-28').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#3ECF8E',
  },
  {
    id: 'ph-24',
    name: 'Resend',
    slug: 'resend',
    tagline: 'Email for developers',
    description: 'Resend is a modern email API built for developers. It makes it easy to send transactional and marketing emails with beautiful templates, analytics, and a developer-friendly SDK that integrates in minutes.',
    logo: 'https://logo.clearbit.com/resend.com',
    website: 'https://resend.com',
    twitter: 'resend_dev',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2022,
    country: 'United States',
    email: null,
    upvotes: 280,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-02').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 280, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'ph-25',
    name: 'Cal.com',
    slug: 'cal-com',
    tagline: 'Scheduling infrastructure for everyone',
    description: 'Cal.com is an open source scheduling platform that makes it easy to set up and share booking links. It supports round-robin scheduling, team workflows, and integrates with popular calendars and video conferencing tools.',
    logo: 'https://logo.clearbit.com/cal.com',
    website: 'https://cal.com',
    twitter: 'calaborates',
    linkedin: null,
    category: 'SaaS',
    stage: 'Series A',
    teamSize: '51-200',
    foundedYear: 2021,
    country: 'United States',
    email: null,
    upvotes: 250,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-12').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 250, perks: 0 },
    logoColor: '#292929',
  },
  {
    id: 'ph-26',
    name: 'Tally',
    slug: 'tally',
    tagline: 'The simplest way to create forms',
    description: 'Tally is a form builder that is free and unlimited. It works like a document, making it incredibly easy to create surveys, quizzes, sign-up forms, and more without any coding or design skills required.',
    logo: 'https://logo.clearbit.com/tally.so',
    website: 'https://tally.so',
    twitter: 'tallyforms',
    linkedin: null,
    category: 'SaaS',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2020,
    country: 'Belgium',
    email: null,
    upvotes: 230,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-15').toISOString(),
    updatedAt: new Date('2025-04-10').toISOString(),
    _count: { votes: 230, perks: 0 },
    logoColor: '#FDD835',
  },
  {
    id: 'ph-27',
    name: 'Aha!',
    slug: 'aha',
    tagline: 'Product development roadmap software',
    description: 'Aha! is a comprehensive product roadmap and strategy platform used by product managers to set strategy, capture ideas, prioritize features, and share visual roadmaps with stakeholders and development teams.',
    logo: 'https://logo.clearbit.com/aha.io',
    website: 'https://www.aha.io',
    twitter: 'aha_io',
    linkedin: null,
    category: 'Business',
    stage: 'Growth',
    teamSize: '51-200',
    foundedYear: 2013,
    country: 'United States',
    email: null,
    upvotes: 200,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date('2025-04-09').toISOString(),
    _count: { votes: 200, perks: 0 },
    logoColor: '#7B68EE',
  },
  {
    id: 'ph-28',
    name: 'Durable',
    slug: 'durable',
    tagline: 'Build a website in 30 seconds with AI',
    description: 'Durable is an AI website builder for small businesses. It generates complete, professional websites in seconds using AI, including copy, images, and contact forms, making it easy for anyone to establish an online presence.',
    logo: 'https://logo.clearbit.com/durable.co',
    website: 'https://durable.co',
    twitter: null,
    linkedin: null,
    category: 'Business',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2022,
    country: 'Canada',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-08').toISOString(),
    updatedAt: new Date('2025-04-08').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#3B82F6',
  },
  {
    id: 'ph-29',
    name: 'Maze',
    slug: 'maze',
    tagline: 'Product research, powered by AI',
    description: 'Maze is an AI-driven product research and usability testing platform. It enables teams to test prototypes, run surveys, and gather actionable user insights quickly, replacing slow traditional research methods with rapid, data-driven decisions.',
    logo: 'https://logo.clearbit.com/maze.co',
    website: 'https://maze.co',
    twitter: 'mazedesign',
    linkedin: null,
    category: 'Design',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2018,
    country: 'France',
    email: null,
    upvotes: 180,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-28').toISOString(),
    updatedAt: new Date('2025-04-07').toISOString(),
    _count: { votes: 180, perks: 0 },
    logoColor: '#635BFF',
  },
  {
    id: 'ph-30',
    name: 'Carrd',
    slug: 'carrd',
    tagline: 'Simple, free, fully responsive one-page sites',
    description: 'Carrd is a simple, free website builder for creating beautiful, fully responsive one-page sites. Built for simplicity, it lets anyone launch a professional web presence in minutes with its drag-and-drop editor and modern templates.',
    logo: 'https://logo.clearbit.com/carrd.co',
    website: 'https://carrd.co',
    twitter: 'carrd_co',
    linkedin: null,
    category: 'Design',
    stage: 'Seed',
    teamSize: '1-5',
    foundedYear: 2016,
    country: 'United States',
    email: null,
    upvotes: 300,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-22').toISOString(),
    updatedAt: new Date('2025-04-06').toISOString(),
    _count: { votes: 300, perks: 0 },
    logoColor: '#1C1C1C',
  },
  {
    id: 'ph-31',
    name: 'TubeBuddy',
    slug: 'tubebuddy',
    tagline: 'YouTube Growth and Management Tool',
    description: 'TubeBuddy is a browser extension for YouTube creators that provides tools for keyword research, SEO optimization, bulk processing, A/B testing thumbnails, and analytics to grow and manage YouTube channels effectively.',
    logo: 'https://logo.clearbit.com/tubebuddy.com',
    website: 'https://www.tubebuddy.com',
    twitter: 'TubeBuddyHQ',
    linkedin: null,
    category: 'Marketing',
    stage: 'Growth',
    teamSize: '21-50',
    foundedYear: 2014,
    country: 'United States',
    email: null,
    upvotes: 220,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-30').toISOString(),
    updatedAt: new Date('2025-04-05').toISOString(),
    _count: { votes: 220, perks: 0 },
    logoColor: '#FF0000',
  },
  {
    id: 'ph-32',
    name: '1Password',
    slug: '1password',
    tagline: "The password manager that's as simple as it is secure",
    description: '1Password provides secure password and secrets management for individuals, families, and businesses. It stores and autofills passwords, credit cards, and sensitive data across all devices with end-to-end encryption.',
    logo: 'https://logo.clearbit.com/1password.com',
    website: 'https://1password.com',
    twitter: '1Password',
    linkedin: null,
    category: 'SaaS',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2005,
    country: 'Canada',
    email: null,
    upvotes: 400,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-28').toISOString(),
    updatedAt: new Date('2025-04-04').toISOString(),
    _count: { votes: 400, perks: 0 },
    logoColor: '#1A8CFF',
  },
  {
    id: 'ph-33',
    name: 'Notion AI',
    slug: 'notion-ai',
    tagline: 'Your connected workspace with AI',
    description: 'Notion AI is an all-in-one workspace enhanced with AI writing and search capabilities. It combines docs, wikis, projects, and databases with intelligent AI that can summarize, write, translate, and automate workflows across your entire workspace.',
    logo: 'https://logo.clearbit.com/notion.so',
    website: 'https://www.notion.so',
    twitter: 'NotionHQ',
    linkedin: null,
    category: 'Productivity',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2016,
    country: 'United States',
    email: null,
    upvotes: 500,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-12').toISOString(),
    updatedAt: new Date('2025-04-03').toISOString(),
    _count: { votes: 500, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'ph-34',
    name: 'Linear',
    slug: 'linear',
    tagline: 'The issue tracking tool built for speed',
    description: 'Linear is a modern issue tracking tool designed for speed and efficiency. It streamlines software project management with keyboard shortcuts, real-time collaboration, and automated workflows that help teams ship faster.',
    logo: 'https://logo.clearbit.com/linear.app',
    website: 'https://linear.app',
    twitter: 'linear_app',
    linkedin: null,
    category: 'Productivity',
    stage: 'Growth',
    teamSize: '51-200',
    foundedYear: 2019,
    country: 'United States',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-02-05').toISOString(),
    updatedAt: new Date('2025-04-02').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#5E6AD2',
  },
  {
    id: 'ph-35',
    name: 'Vercel',
    slug: 'vercel',
    tagline: 'Your complete frontend platform',
    description: 'Vercel is the frontend cloud platform for deploying web applications. It provides instant previews, edge functions, serverless APIs, and an optimized global CDN that makes web development and deployment faster than ever.',
    logo: 'https://logo.clearbit.com/vercel.com',
    website: 'https://vercel.com',
    twitter: 'vercel',
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2015,
    country: 'United States',
    email: null,
    upvotes: 300,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-02').toISOString(),
    updatedAt: new Date('2025-04-01').toISOString(),
    _count: { votes: 300, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'ph-36',
    name: 'Stripe',
    slug: 'stripe',
    tagline: 'Financial infrastructure for the internet',
    description: 'Stripe is an online payment processing platform that provides financial infrastructure for internet businesses. It handles payments, subscriptions, payouts, and fraud prevention with a developer-friendly API trusted by millions of companies worldwide.',
    logo: 'https://logo.clearbit.com/stripe.com',
    website: 'https://stripe.com',
    twitter: 'stripe',
    linkedin: null,
    category: 'Finance',
    stage: 'Growth',
    teamSize: '201-500',
    foundedYear: 2010,
    country: 'United States',
    email: null,
    upvotes: 450,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-01-08').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 450, perks: 0 },
    logoColor: '#635BFF',
  },
  // ─── From F6S (UK Startups) ───
  {
    id: 'f6s-1',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    tagline: 'AI voice synthesis and text-to-speech platform',
    description: 'ElevenLabs specializes in AI-driven voice synthesis, offering advanced text-to-speech (TTS) technology that creates ultra-realistic, human-like voices. Their platform supports voice cloning, dubbing, and multilingual audio generation for content creators and enterprises.',
    logo: null,
    website: 'https://elevenlabs.io',
    twitter: 'elevenlabsio',
    linkedin: null,
    category: 'AI',
    stage: 'Series C',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'United Kingdom',
    email: null,
    upvotes: 680,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 680, perks: 0 },
    logoColor: '#000000',
  },
  {
    id: 'f6s-2',
    name: 'Synthesia',
    slug: 'synthesia',
    tagline: 'AI video generation platform for enterprise',
    description: 'Synthesia is an AI-powered video generation platform that enables users to create professional videos using AI avatars. It eliminates the need for cameras, studios, and actors, making video production accessible to everyone.',
    logo: null,
    website: 'https://www.synthesia.io',
    twitter: 'synthesia_io',
    linkedin: null,
    category: 'AI',
    stage: 'Series C',
    teamSize: '51-200',
    foundedYear: 2017,
    country: 'United Kingdom',
    email: null,
    upvotes: 620,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 620, perks: 0 },
    logoColor: '#5D5FEF',
  },
  {
    id: 'f6s-3',
    name: 'Wayve',
    slug: 'wayve',
    tagline: 'Autonomous driving powered by foundation models',
    description: 'Wayve is developing the first embodied AI for autonomous driving. Their AI learns to drive using end-to-end deep learning, leveraging foundation models and reinforcement learning to navigate complex urban environments safely.',
    logo: null,
    website: 'https://wayve.ai',
    twitter: 'wayve_ai',
    linkedin: null,
    category: 'AI',
    stage: 'Series C',
    teamSize: '201-500',
    foundedYear: 2017,
    country: 'United Kingdom',
    email: null,
    upvotes: 550,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-10').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 550, perks: 0 },
    logoColor: '#1CE783',
  },
  {
    id: 'f6s-4',
    name: 'Encord',
    slug: 'encord',
    tagline: 'AI-native data annotation and model evaluation',
    description: 'Encord provides an AI-native platform for data annotation, model evaluation, and quality assurance. It helps machine learning teams build high-quality training datasets for computer vision, medical imaging, and multi-modal AI applications.',
    logo: null,
    website: 'https://encord.com',
    twitter: 'encord_team',
    linkedin: null,
    category: 'AI',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2020,
    country: 'United Kingdom',
    email: null,
    upvotes: 420,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-12').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 420, perks: 0 },
    logoColor: '#7C3AED',
  },
  {
    id: 'f6s-5',
    name: 'Nscale',
    slug: 'nscale',
    tagline: 'Sovereign and sustainable AI cloud platform',
    description: 'Nscale is a full-stack, sovereign, and sustainable AI cloud platform providing GPU infrastructure for AI workloads. It offers high-performance compute, networking, and storage optimized for training and deploying AI models at scale.',
    logo: null,
    website: 'https://nscale.com',
    twitter: null,
    linkedin: null,
    category: 'Developer Tools',
    stage: 'Series B',
    teamSize: '21-50',
    foundedYear: 2022,
    country: 'United Kingdom',
    email: null,
    upvotes: 380,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-14').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 380, perks: 0 },
    logoColor: '#2563EB',
  },
  {
    id: 'f6s-6',
    name: 'ProdPad',
    slug: 'prodpad',
    tagline: 'Complete product management toolkit',
    description: 'ProdPad is a complete product management toolkit that promotes collaboration and empowers product managers to build great products. It provides roadmapping, idea management, feedback collection, and prioritization tools.',
    logo: null,
    website: 'https://www.prodpad.com',
    twitter: 'prodpad',
    linkedin: null,
    category: 'Business',
    stage: 'Growth',
    teamSize: '21-50',
    foundedYear: 2012,
    country: 'United Kingdom',
    email: null,
    upvotes: 290,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-16').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 290, perks: 0 },
    logoColor: '#E8435A',
  },
  {
    id: 'f6s-7',
    name: 'OLIX',
    slug: 'olix',
    tagline: 'Building AI chips faster and cheaper than NVIDIA',
    description: 'OLIX is building the next generation of AI chips designed to be faster and more cost-effective than existing solutions. The company raised $220M to develop proprietary hardware for deploying frontier AI models efficiently.',
    logo: null,
    website: 'https://olix.com',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'United Kingdom',
    email: null,
    upvotes: 520,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-18').toISOString(),
    updatedAt: new Date('2025-04-14').toISOString(),
    _count: { votes: 520, perks: 0 },
    logoColor: '#0EA5E9',
  },
  {
    id: 'f6s-8',
    name: 'Descycle',
    slug: 'descycle',
    tagline: 'Green chemistry for sustainable manufacturing',
    description: 'Descycle is a cleantech startup pioneering green chemistry solutions for sustainable manufacturing. Their technology enables the extraction and recycling of critical metals without toxic chemicals, reducing environmental impact.',
    logo: null,
    website: 'https://descycle.co.uk',
    twitter: null,
    linkedin: null,
    category: 'Cleantech',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2020,
    country: 'United Kingdom',
    email: null,
    upvotes: 240,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-20').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 240, perks: 0 },
    logoColor: '#10B981',
  },
  {
    id: 'f6s-9',
    name: 'CLUBZER0',
    slug: 'clubzero',
    tagline: 'Zero-waste packaging delivery and return system',
    description: 'CLUBZER0 provides a circular packaging platform that eliminates single-use waste. Their returnable container system works with restaurants, cafes, and retailers to deliver food and drinks in reusable packaging.',
    logo: null,
    website: 'https://www.clubzero.co',
    twitter: 'clubzero_co',
    linkedin: null,
    category: 'Cleantech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2019,
    country: 'United Kingdom',
    email: null,
    upvotes: 310,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-03-22').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 310, perks: 0 },
    logoColor: '#22C55E',
  },
  // ─── From Les Pepites Tech (France) ───
  {
    id: 'lp-1',
    name: 'Leia',
    slug: 'leia-health',
    tagline: 'Health management platform for nurseries',
    description: 'Leia is the first custom-built health management tool for nurseries and childcare centers. It digitizes health records, tracks children development milestones, and simplifies administrative tasks for childcare professionals.',
    logo: null,
    website: 'https://www.leia.fr',
    twitter: null,
    linkedin: null,
    category: 'Health',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2023,
    country: 'France',
    email: null,
    upvotes: 480,
    featured: true,
    status: 'active',
    createdAt: new Date('2025-04-01').toISOString(),
    updatedAt: new Date('2025-04-20').toISOString(),
    _count: { votes: 480, perks: 0 },
    logoColor: '#EC4899',
  },
  {
    id: 'lp-2',
    name: 'Ventureo Academy',
    slug: 'ventureo-academy',
    tagline: 'Adaptive e-learning platform for employee training',
    description: 'Ventureo Academy is an adaptive e-learning platform that transforms employees into high performers. It uses AI to personalize training paths and delivers interactive courses tailored to individual learning styles and career goals.',
    logo: null,
    website: 'https://www.ventureo-academy.com',
    twitter: null,
    linkedin: null,
    category: 'Education',
    stage: 'Pre-seed',
    teamSize: '6-20',
    foundedYear: 2023,
    country: 'France',
    email: null,
    upvotes: 450,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-03').toISOString(),
    updatedAt: new Date('2025-04-19').toISOString(),
    _count: { votes: 450, perks: 0 },
    logoColor: '#F59E0B',
  },
  {
    id: 'lp-3',
    name: 'The Webskills',
    slug: 'the-webskills',
    tagline: 'Digital skills training and certification platform',
    description: 'The Webskills provides comprehensive digital skills training programs with industry-recognized certifications. Their platform offers courses in web development, data analysis, digital marketing, and UX design.',
    logo: null,
    website: 'https://www.thewebskills.com',
    twitter: null,
    linkedin: null,
    category: 'Education',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'France',
    email: null,
    upvotes: 350,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-05').toISOString(),
    updatedAt: new Date('2025-04-18').toISOString(),
    _count: { votes: 350, perks: 0 },
    logoColor: '#8B5CF6',
  },
  {
    id: 'lp-4',
    name: 'SafeKeeper',
    slug: 'safekeeper',
    tagline: 'Digital security and data protection platform',
    description: 'SafeKeeper provides cybersecurity solutions for small and medium businesses. It offers real-time threat detection, vulnerability assessment, and compliance management to protect digital assets and sensitive data.',
    logo: null,
    website: 'https://www.safekeeper.fr',
    twitter: null,
    linkedin: null,
    category: 'Security',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2023,
    country: 'France',
    email: null,
    upvotes: 370,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-07').toISOString(),
    updatedAt: new Date('2025-04-17').toISOString(),
    _count: { votes: 370, perks: 0 },
    logoColor: '#DC2626',
  },
  {
    id: 'lp-5',
    name: 'Lokaly',
    slug: 'lokaly',
    tagline: 'Hyperlocal commerce platform connecting shops and consumers',
    description: 'Lokaly is a hyperlocal commerce platform that connects neighborhood shops with local consumers. It enables small retailers to sell online and offer local delivery, strengthening community commerce.',
    logo: null,
    website: 'https://www.lokaly.fr',
    twitter: null,
    linkedin: null,
    category: 'E-Commerce',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2022,
    country: 'France',
    email: null,
    upvotes: 330,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-09').toISOString(),
    updatedAt: new Date('2025-04-16').toISOString(),
    _count: { votes: 330, perks: 0 },
    logoColor: '#F97316',
  },
  {
    id: 'lp-6',
    name: 'CopilotePME',
    slug: 'copilotepme',
    tagline: 'AI assistant for artisans and small businesses',
    description: 'CopilotePME is an intelligent all-in-one assistant designed specifically for artisans and small businesses (TPE). It automates administrative tasks, invoicing, customer management, and provides AI-powered business recommendations.',
    logo: null,
    website: 'https://www.copilotepme.fr',
    twitter: null,
    linkedin: null,
    category: 'AI',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2024,
    country: 'France',
    email: null,
    upvotes: 400,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-11').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
    _count: { votes: 400, perks: 0 },
    logoColor: '#3B82F6',
  },
  {
    id: 'lp-8',
    name: 'URLR',
    slug: 'urlr',
    tagline: 'Smart URL shortener and link management platform',
    description: 'URLR is a comprehensive URL shortener and link management platform. It provides analytics, custom domains, QR code generation, and team collaboration features for marketers and businesses managing large volumes of links.',
    logo: null,
    website: 'https://urlr.me',
    twitter: null,
    linkedin: null,
    category: 'Marketing',
    stage: 'Growth',
    teamSize: '6-20',
    foundedYear: 2020,
    country: 'France',
    email: null,
    upvotes: 310,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-15').toISOString(),
    updatedAt: new Date('2025-04-13').toISOString(),
    _count: { votes: 310, perks: 0 },
    logoColor: '#7C3AED',
  },
  {
    id: 'lp-9',
    name: 'Lexaro',
    slug: 'lexaro',
    tagline: 'Legal tech platform for contract management',
    description: 'Lexaro is a legal technology platform that simplifies contract management for businesses. It uses AI to analyze, draft, and manage legal documents, reducing the time and cost associated with legal operations.',
    logo: null,
    website: 'https://www.lexaro.fr',
    twitter: null,
    linkedin: null,
    category: 'Legal',
    stage: 'Pre-seed',
    teamSize: '6-20',
    foundedYear: 2023,
    country: 'France',
    email: null,
    upvotes: 270,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-17').toISOString(),
    updatedAt: new Date('2025-04-12').toISOString(),
    _count: { votes: 270, perks: 0 },
    logoColor: '#1D4ED8',
  },
  {
    id: 'lp-10',
    name: 'noo-mediation',
    slug: 'noo-mediation',
    tagline: 'Online dispute resolution and mediation platform',
    description: 'noo-mediation is a platform for legal information and confidential, rapid online dispute resolution. It enables parties to resolve conflicts through digital mediation without going to court, saving time and money.',
    logo: null,
    website: 'https://www.noo-mediation.fr',
    twitter: null,
    linkedin: null,
    category: 'Legal',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2022,
    country: 'France',
    email: null,
    upvotes: 340,
    featured: false,
    status: 'active',
    createdAt: new Date('2025-04-19').toISOString(),
    updatedAt: new Date('2025-04-11').toISOString(),
    _count: { votes: 340, perks: 0 },
    logoColor: '#059669',
  },
]

export const fallbackWeeklyWinners = [
  { rank: 1, medal: 'gold', points: 800, ...fallbackStartups[0] },
  { rank: 2, medal: 'silver', points: 743, ...fallbackStartups[1] },
  { rank: 3, medal: 'bronze', points: 620, ...fallbackStartups[2] },
]

export const fallbackPerks: Record<string, { id: string; title: string; description: string; discount: string | null; url: string }[]> = {
  'metagpt': [
    { id: 'fp-1', title: 'Free Trial', description: 'Get 3 months free on any Atoms plan', discount: '100% off for 3 months', url: '#' },
    { id: 'fp-2', title: 'Startup Discount', description: '50% off for early-stage startups', discount: '50% off first year', url: '#' },
  ],
  'sider-5': [
    { id: 'fp-3', title: 'Pro Upgrade', description: 'Free Pro plan for Revolaunch community members', discount: 'Free Pro tier', url: '#' },
  ],
  'dreamina': [
    { id: 'fp-4', title: 'Free Credits', description: '500 free AI generation credits', discount: '500 credits free', url: '#' },
  ],
  'pageon-ai': [
    { id: 'fp-5', title: 'Demo Access', description: 'Full access to all PageOn.AI 2.0 features for 14 days', discount: '14-day free trial', url: '#' },
  ],
  'cursor': [
    { id: 'fp-6', title: 'Pro Month', description: 'Get one free month of Cursor Pro', discount: '1 month free', url: '#' },
  ],
  'bolt-new': [
    { id: 'fp-7', title: 'Extra Compute', description: 'Double compute credits for your first month', discount: '2x credits', url: '#' },
  ],
  'lovable': [
    { id: 'fp-8', title: 'Team Discount', description: '20% off the first 3 months on any team plan', discount: '20% off for 3 months', url: '#' },
  ],
  'stripe': [
    { id: 'fp-9', title: 'Waived Fees', description: 'First $50K in processing fees waived for new startups', discount: '$50K fee-free', url: '#' },
  ],
  'vercel': [
    { id: 'fp-10', title: 'Pro Plan', description: '2 months free on Vercel Pro', discount: '2 months free', url: '#' },
  ],
}

export const fallbackCategories = [
  { name: 'AI', count: 14, icon: '🤖' },
  { name: 'Developer Tools', count: 12, icon: '🛠️' },
  { name: 'Design', count: 4, icon: '🎨' },
  { name: 'SaaS', count: 3, icon: '☁️' },
  { name: 'Productivity', count: 3, icon: '⚡' },
  { name: 'Business', count: 4, icon: '🏢' },
  { name: 'Marketing', count: 3, icon: '📣' },
  { name: 'Finance', count: 1, icon: '💰' },
  { name: 'Cleantech', count: 2, icon: '🌱' },
  { name: 'Health', count: 1, icon: '🏥' },
  { name: 'Education', count: 2, icon: '📚' },
  { name: 'Security', count: 1, icon: '🔒' },
  { name: 'E-Commerce', count: 1, icon: '🛒' },
  { name: 'Legal', count: 2, icon: '⚖️' },
]

export const fallbackStats = {
  totalStartups: 55,
  totalVotes: 21635,
  totalCategories: 14,
  featuredCount: 8,
  topCategories: [
    { name: 'AI', count: 14 },
    { name: 'Developer Tools', count: 12 },
    { name: 'Design', count: 4 },
    { name: 'Business', count: 4 },
    { name: 'Education', count: 3 },
  ],
  stages: [
    { name: 'Growth', count: 14 },
    { name: 'Seed', count: 10 },
    { name: 'Series A', count: 9 },
    { name: 'Pre-seed', count: 9 },
    { name: 'Series B', count: 7 },
    { name: 'Series C', count: 3 },
    { name: 'Series D', count: 0 },
  ],
  countries: [
    { name: 'United States', count: 24 },
    { name: 'France', count: 9 },
    { name: 'United Kingdom', count: 9 },
    { name: 'China', count: 4 },
    { name: 'Canada', count: 2 },
    { name: 'Germany', count: 1 },
    { name: 'India', count: 1 },
    { name: 'Denmark', count: 1 },
    { name: 'Singapore', count: 1 },
    { name: 'Belgium', count: 1 },
  ],
  weeklyGrowth: [
    { week: 'Week 1', startups: 6 },
    { week: 'Week 2', startups: 12 },
    { week: 'Week 3', startups: 19 },
    { week: 'Week 4', startups: 25 },
    { week: 'Week 5', startups: 30 },
    { week: 'Week 6', startups: 36 },
    { week: 'Week 7', startups: 45 },
    { week: 'Week 8', startups: 55 },
  ],
}

export interface CommunityBoard {
  id: string
  name: string
  description: string
  icon: string
  itemCount: number
  color: string
  items: CommunityBoardItem[]
}

export interface CommunityBoardItem {
  id: string
  title: string
  description: string
  author: string
  authorAvatar?: string
  createdAt: string
  upvotes: number
  tags: string[]
  startup?: string
  mrr?: number
  link?: string
}

export const fallbackCommunityBoards: CommunityBoard[] = [
  {
    id: 'mrr-board',
    name: 'MRR Board',
    description: 'Share your monthly recurring revenue milestones',
    icon: '📊',
    itemCount: 42,
    color: '#22C55E',
    items: [
      {
        id: 'mrr-1',
        title: 'Cursor hits $100K ARR milestone!',
        description: 'AI code editor adoption is accelerating. Teams are switching from traditional IDEs at record pace.',
        author: 'Michael Truell',
        createdAt: '2025-04-18T10:30:00Z',
        upvotes: 156,
        tags: ['Developer Tools', 'Milestone'],
        startup: 'Cursor',
        mrr: 8300,
      },
      {
        id: 'mrr-2',
        title: 'Lovable surpasses $2M ARR',
        description: 'From GPT Engineer to Lovable - the AI app builder revolution is real. 50K+ apps generated.',
        author: 'Anton Osika',
        createdAt: '2025-04-17T14:00:00Z',
        upvotes: 134,
        tags: ['AI', 'SaaS'],
        startup: 'Lovable',
        mrr: 166000,
      },
      {
        id: 'mrr-3',
        title: 'Mailgo crosses $50K MRR',
        description: 'Cold email outreach with AI deliverability is resonating with B2B sales teams worldwide.',
        author: 'David Zhang',
        createdAt: '2025-04-16T09:15:00Z',
        upvotes: 98,
        tags: ['Marketing', 'SaaS'],
        startup: 'Mailgo',
        mrr: 50000,
      },
      {
        id: 'mrr-4',
        title: 'Kibo UI community is booming',
        description: 'Open source components for shadcn/ui reached 5K GitHub stars and growing fast.',
        author: 'Sasha Khamosh',
        createdAt: '2025-04-15T16:45:00Z',
        upvotes: 87,
        tags: ['Open Source', 'Developer Tools'],
        startup: 'Kibo UI',
        mrr: 0,
      },
    ],
  },
  {
    id: 'weekly-board',
    name: 'Weekly Board',
    description: 'Track your weekly progress and compete for top rankings',
    icon: '🏆',
    itemCount: 1420,
    color: '#F59E0B',
    items: [
      {
        id: 'wb-1',
        title: 'MGX (Atoms) - 800 pts this week',
        description: 'Multi-agent AI dev team went viral on PH. 800+ upvotes and thousands of new signups.',
        author: 'Jared Zoneraich',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 800,
        tags: ['Weekly Winner'],
        startup: 'MGX (Now Atoms)',
      },
      {
        id: 'wb-2',
        title: 'Sider 5.0 - 743 pts this week',
        description: 'Deep Research feature is a game-changer. Users love scanning 100+ sources for comprehensive reports.',
        author: 'Kevin Zhang',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 743,
        tags: ['Weekly Runner-up'],
        startup: 'Sider 5.0',
      },
      {
        id: 'wb-3',
        title: 'Dreamina - 620 pts this week',
        description: 'AI creative suite from ByteDance stunning the PH community with poster and logo generation quality.',
        author: 'Dreamina Team',
        createdAt: '2025-04-20T23:59:00Z',
        upvotes: 620,
        tags: ['Weekly 3rd Place'],
        startup: 'Dreamina',
      },
    ],
  },
  {
    id: 'raising-capital',
    name: 'Raising Capital',
    description: 'Connect with investors and showcase your fundraising journey',
    icon: '💰',
    itemCount: 89,
    color: '#3B82F6',
    items: [
      {
        id: 'rc-1',
        title: 'Lovable raises Series A - $25M',
        description: 'Building the future of AI-powered software development. Backed by top-tier VCs to scale our AI builder platform.',
        author: 'Anton Osika',
        createdAt: '2025-04-18T08:00:00Z',
        upvotes: 245,
        tags: ['Series A', 'AI'],
        startup: 'Lovable',
        link: '#',
      },
      {
        id: 'rc-2',
        title: 'Durable raises $14M Series A',
        description: 'AI website builder for SMBs. Already helping 100K+ businesses establish their online presence in seconds.',
        author: 'Marc Lou',
        createdAt: '2025-04-17T11:30:00Z',
        upvotes: 178,
        tags: ['Series A', 'AI', 'Business'],
        startup: 'Durable',
        link: '#',
      },
    ],
  },
  {
    id: 'job-board',
    name: 'Job Board',
    description: 'Find and post jobs at the most innovative startups',
    icon: '💼',
    itemCount: 0,
    color: '#8B5CF6',
    items: [],
  },
  {
    id: 'open-to-acquisition',
    name: 'Open to Acquisition',
    description: 'Startups open to being acquired',
    icon: '🤝',
    itemCount: 12,
    color: '#EC4899',
    items: [
      {
        id: 'oa-1',
        title: 'Kibo UI open to acquisition',
        description: 'Leading open-source component library for shadcn/ui. 5K GitHub stars, strong community engagement.',
        author: 'Sasha Khamosh',
        createdAt: '2025-04-15T10:00:00Z',
        upvotes: 67,
        tags: ['Open Source', 'Developer Tools'],
        startup: 'Kibo UI',
      },
      {
        id: 'oa-2',
        title: 'next-forge exploring strategic partnerships',
        description: 'Opinionated Next.js boilerplate with growing adoption. 2K+ developers using the framework.',
        author: 'Middlefield Team',
        createdAt: '2025-04-14T14:30:00Z',
        upvotes: 43,
        tags: ['Developer Tools', 'Frameworks'],
        startup: 'next-forge',
      },
    ],
  },
  {
    id: 'perks-directory',
    name: 'Perks Directory',
    description: 'Exclusive deals and perks for the startup community',
    icon: '🎁',
    itemCount: 12,
    color: '#F97316',
    items: [
      {
        id: 'pd-1',
        title: 'MGX (Atoms) - 3 months free',
        description: 'Get 3 months free on any Atoms plan. Perfect for teams building with AI agents.',
        author: 'MGX (Now Atoms)',
        createdAt: '2025-04-10T00:00:00Z',
        upvotes: 312,
        tags: ['AI', 'DevTools', 'Free Trial'],
        startup: 'MGX (Now Atoms)',
      },
      {
        id: 'pd-2',
        title: 'Sider 5.0 - Free Pro upgrade',
        description: 'Activate a free Pro plan for Revolaunch members. Deep Research included.',
        author: 'Sider 5.0',
        createdAt: '2025-04-08T00:00:00Z',
        upvotes: 256,
        tags: ['AI', 'Productivity', 'Free Trial'],
        startup: 'Sider 5.0',
      },
      {
        id: 'pd-3',
        title: 'Stripe - $50K fee-free processing',
        description: 'First $50K in payment processing fees waived. Ideal for new startups.',
        author: 'Stripe',
        createdAt: '2025-04-05T00:00:00Z',
        upvotes: 445,
        tags: ['Finance', 'Payments', 'Free Trial'],
        startup: 'Stripe',
      },
      {
        id: 'pd-4',
        title: 'Vercel - 2 months Pro free',
        description: 'Get 2 months of Vercel Pro with unlimited bandwidth and team collaboration.',
        author: 'Vercel',
        createdAt: '2025-04-02T00:00:00Z',
        upvotes: 289,
        tags: ['Developer Tools', 'Hosting', 'Free Trial'],
        startup: 'Vercel',
      },
    ],
  },
]

// Helper functions for category/stage icons and colors
const categoryIcons: Record<string, string> = {
  'AI': '🤖',
  'Developer Tools': '🛠️',
  'Design': '🎨',
  'SaaS': '☁️',
  'Productivity': '⚡',
  'Business': '🏢',
  'Marketing': '📣',
  'Finance': '💰',
  'Cybersecurity': '🔒',
}

const categoryColors: Record<string, string> = {
  'AI': '#8B5CF6',
  'Developer Tools': '#0EA5E9',
  'Design': '#EC4899',
  'SaaS': '#3B82F6',
  'Productivity': '#F59E0B',
  'Business': '#10B981',
  'Marketing': '#F97316',
  'Finance': '#635BFF',
  'Cybersecurity': '#EF4444',
}

const stageColors: Record<string, string> = {
  'Pre-seed': '#6B7280',
  'Seed': '#10B981',
  'Series A': '#3B82F6',
  'Series B': '#8B5CF6',
  'Series C': '#EC4899',
  'Growth': '#F59E0B',
}

export function getCategoryIcon(category: string): string {
  return categoryIcons[category] || '🚀'
}

export function getCategoryColor(category: string): string {
  return categoryColors[category] || '#6B7280'
}

export function getStageColor(stage: string): string {
  return stageColors[stage] || '#6B7280'
}
