import { db } from '@/lib/db'

const categories = [
  'AI / Machine Learning',
  'SaaS',
  'FinTech',
  'HealthTech',
  'EdTech',
  'E-Commerce',
  'DevTools',
  'Cybersecurity',
  'Climate Tech',
  'Web3 / Blockchain',
  'Productivity',
  'Social / Community',
  'Marketing',
  'HR / Recruiting',
  'Real Estate Tech',
  'Food & Beverage',
  'Gaming',
  'Mobility',
  'Logistics',
  'Other',
]

const startups = [
  {
    name: 'NeuralForge',
    slug: 'neuralforge',
    tagline: 'AI-powered code review that catches bugs before they ship',
    description: 'NeuralForge uses advanced machine learning models to analyze your codebase in real-time, identifying potential bugs, security vulnerabilities, and performance issues. Unlike traditional linters, NeuralForge understands context and intent, providing actionable suggestions that actually improve code quality. Compatible with all major IDEs and CI/CD pipelines.',
    website: 'https://neuralforge.dev',
    twitter: 'neuralforge',
    category: 'AI / Machine Learning',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    featured: true,
    upvotes: 342,
    logo: null,
  },
  {
    name: 'PayStream',
    slug: 'paystream',
    tagline: 'Instant cross-border payments for freelancers and SMBs',
    description: 'PayStream eliminates the pain of international payments. Send and receive money in 50+ currencies with zero fees, instant settlement, and transparent exchange rates. Built specifically for freelancers, remote teams, and small businesses who need reliable cross-border payment solutions without the banking overhead.',
    website: 'https://paystream.io',
    twitter: 'paystream',
    category: 'FinTech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United Kingdom',
    featured: true,
    upvotes: 287,
    logo: null,
  },
  {
    name: 'CloudNest',
    slug: 'cloudnest',
    tagline: 'Deploy infrastructure as code with visual drag-and-drop',
    description: 'CloudNest makes infrastructure management accessible to everyone. Instead of writing complex Terraform or CloudFormation files, visually design your cloud architecture with an intuitive drag-and-drop interface. CloudNest generates optimized, production-ready infrastructure code that works across AWS, GCP, and Azure.',
    website: 'https://cloudnest.dev',
    twitter: 'cloudnest',
    category: 'DevTools',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Germany',
    featured: true,
    upvotes: 256,
    logo: null,
  },
  {
    name: 'MediScan AI',
    slug: 'mediscan-ai',
    tagline: 'AI diagnostic assistant for radiologists and clinicians',
    description: 'MediScan AI accelerates medical imaging diagnostics by providing AI-powered second opinions for X-rays, CT scans, and MRIs. Our FDA-cleared algorithms have been trained on millions of medical images and can detect anomalies with 97.3% accuracy, reducing diagnostic time by up to 60% while maintaining full physician oversight.',
    website: 'https://mediscan.ai',
    twitter: 'mediscan_ai',
    category: 'HealthTech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Israel',
    featured: true,
    upvotes: 234,
    logo: null,
  },
  {
    name: 'LearnLoop',
    slug: 'learnloop',
    tagline: 'Personalized AI tutoring that adapts to every learning style',
    description: 'LearnLoop is revolutionizing education with AI tutors that truly understand each student. By analyzing learning patterns, strengths, and weaknesses, LearnLoop creates personalized curricula that adapt in real-time. From K-12 to professional development, our platform delivers 1-on-1 tutoring at scale with proven results.',
    website: 'https://learnloop.ai',
    twitter: 'learnloop',
    category: 'EdTech',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Canada',
    featured: false,
    upvotes: 198,
    logo: null,
  },
  {
    name: 'GreenGrid',
    slug: 'greengrid',
    tagline: 'Smart energy management platform for commercial buildings',
    description: 'GreenGrid helps commercial property owners reduce energy costs by up to 40% through AI-optimized energy management. Our IoT sensors and machine learning algorithms analyze building usage patterns in real-time, automatically adjusting HVAC, lighting, and power distribution for maximum efficiency without sacrificing comfort.',
    website: 'https://greengrid.energy',
    twitter: 'greengrid_energy',
    category: 'Climate Tech',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'Netherlands',
    featured: false,
    upvotes: 176,
    logo: null,
  },
  {
    name: 'StackBot',
    slug: 'stackbot',
    tagline: 'AI customer support agent trained on your entire documentation',
    description: 'StackBot creates intelligent customer support agents that actually understand your product. By ingesting your docs, APIs, knowledge base, and past support tickets, StackBot provides accurate, contextual answers 24/7. Reduce support volume by 70% while improving customer satisfaction scores.',
    website: 'https://stackbot.io',
    twitter: 'stackbot',
    category: 'SaaS',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Australia',
    featured: false,
    upvotes: 163,
    logo: null,
  },
  {
    name: 'ChainVault',
    slug: 'chainvault',
    tagline: 'Institutional-grade DeFi custody and treasury management',
    description: 'ChainVault bridges the gap between traditional finance and decentralized finance. Our institutional custody solution provides multi-sig security, insurance coverage, and regulatory compliance while enabling access to DeFi yield strategies. Trusted by hedge funds, family offices, and corporate treasuries.',
    website: 'https://chainvault.finance',
    twitter: 'chainvault_fi',
    category: 'Web3 / Blockchain',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'Singapore',
    featured: false,
    upvotes: 152,
    logo: null,
  },
  {
    name: 'FlowMetrics',
    slug: 'flowmetrics',
    tagline: 'Real-time product analytics with built-in AI insights',
    description: 'FlowMetrics gives product teams superpowers with AI-driven analytics that go beyond dashboards. Automatically discover user behavior patterns, predict churn risk, and identify growth opportunities. Our natural language query interface means anyone can ask questions about their data without writing SQL.',
    website: 'https://flowmetrics.com',
    twitter: 'flowmetrics',
    category: 'SaaS',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'France',
    featured: false,
    upvotes: 141,
    logo: null,
  },
  {
    name: 'HireLogic',
    slug: 'hirelogic',
    tagline: 'AI-powered hiring platform that eliminates bias and accelerates recruitment',
    description: 'HireLogic uses AI to transform every step of the hiring process. From intelligent job descriptions and automated candidate sourcing to bias-free resume screening and structured interview guides, HireLogic helps companies build diverse, high-performing teams 3x faster than traditional methods.',
    website: 'https://hirelogic.com',
    twitter: 'hirelogic',
    category: 'HR / Recruiting',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'United States',
    featured: false,
    upvotes: 128,
    logo: null,
  },
  {
    name: 'CyberShield AI',
    slug: 'cybershield-ai',
    tagline: 'Autonomous threat detection and response for SMBs',
    description: 'CyberShield AI provides enterprise-grade cybersecurity for small and medium businesses. Our autonomous AI agents monitor your entire digital infrastructure 24/7, detecting and responding to threats in real-time. No security expertise required — just deploy and let AI handle the rest.',
    website: 'https://cybershield.ai',
    twitter: 'cybershield_ai',
    category: 'Cybersecurity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'Estonia',
    featured: false,
    upvotes: 119,
    logo: null,
  },
  {
    name: 'FreshCart',
    slug: 'freshcart',
    tagline: 'AI-driven grocery delivery with real-time inventory tracking',
    description: 'FreshCart connects consumers directly with local grocery stores and farmers markets. Our AI optimizes delivery routes, predicts demand to reduce food waste, and ensures fresh products arrive within 30 minutes. Partnering with 2,000+ stores across 50 cities to make quality groceries accessible to everyone.',
    website: 'https://freshcart.app',
    twitter: 'freshcart',
    category: 'E-Commerce',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'India',
    featured: false,
    upvotes: 112,
    logo: null,
  },
  {
    name: 'CodePilot',
    slug: 'codepilot',
    tagline: 'AI pair programmer that writes, tests, and deploys with you',
    description: 'CodePilot is more than autocomplete — it is a true AI pair programmer. Understanding your entire codebase architecture, CodePilot can write complete features, generate comprehensive tests, create documentation, and even handle deployment configurations. Works with VS Code, JetBrains, and Vim.',
    website: 'https://codepilot.dev',
    twitter: 'codepilot',
    category: 'DevTools',
    stage: 'Series B',
    teamSize: '51-200',
    foundedYear: 2022,
    country: 'United States',
    featured: false,
    upvotes: 108,
    logo: null,
  },
  {
    name: 'MarketMind',
    slug: 'marketmind',
    tagline: 'AI content marketing platform that generates and optimizes campaigns',
    description: 'MarketMind takes the guesswork out of content marketing. Our AI analyzes your audience, competitors, and industry trends to create data-driven content strategies. From blog posts and social media to email campaigns and landing pages, MarketMind generates high-converting content optimized for every channel.',
    website: 'https://marketmind.ai',
    twitter: 'marketmind_ai',
    category: 'Marketing',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Brazil',
    featured: false,
    upvotes: 95,
    logo: null,
  },
  {
    name: 'PropTech One',
    slug: 'proptech-one',
    tagline: 'Digital platform for fractional real estate investment globally',
    description: 'PropTech One democratizes real estate investing by allowing anyone to invest in premium properties worldwide with as little as $100. Our platform handles everything from property acquisition and management to tenant relations and monthly distributions. Transparent, liquid, and fully regulated.',
    website: 'https://proptechone.com',
    twitter: 'proptech_one',
    category: 'Real Estate Tech',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'UAE',
    featured: false,
    upvotes: 87,
    logo: null,
  },
  {
    name: 'GameForge AI',
    slug: 'gameforge-ai',
    tagline: 'AI platform that generates game assets, levels, and entire games',
    description: 'GameForge AI empowers game developers with AI tools that can generate 2D and 3D assets, design game levels, write narratives, create sound effects, and even prototype complete game concepts. From indie developers to AAA studios, GameForge AI accelerates every stage of game development.',
    website: 'https://gameforge.ai',
    twitter: 'gameforge',
    category: 'Gaming',
    stage: 'Pre-seed',
    teamSize: '1-5',
    foundedYear: 2025,
    country: 'Japan',
    featured: false,
    upvotes: 82,
    logo: null,
  },
  {
    name: 'TaskFlow',
    slug: 'taskflow',
    tagline: 'AI-powered project management that plans and executes automatically',
    description: 'TaskFlow reinvents project management with AI at its core. Instead of manually creating tasks and assigning work, describe your goal and let AI break it down into actionable tasks, assign them based on team skills and availability, predict blockers, and adjust timelines dynamically. Project management, finally automated.',
    website: 'https://taskflow.app',
    twitter: 'taskflow',
    category: 'Productivity',
    stage: 'Seed',
    teamSize: '6-20',
    foundedYear: 2024,
    country: 'South Korea',
    featured: false,
    upvotes: 76,
    logo: null,
  },
  {
    name: 'ShipFast',
    slug: 'shipfast',
    tagline: 'Autonomous logistics platform for D2C brands',
    description: 'ShipFast provides end-to-end logistics solutions for direct-to-consumer brands. From warehousing and inventory management to same-day delivery and returns processing, our AI-optimized platform reduces shipping costs by 35% while delivering a premium unboxing experience that delights customers.',
    website: 'https://shipfast.co',
    twitter: 'shipfast',
    category: 'Logistics',
    stage: 'Series A',
    teamSize: '21-50',
    foundedYear: 2023,
    country: 'United States',
    featured: false,
    upvotes: 71,
    logo: null,
  },
]

async function main() {
  console.log('Seeding database...')

  // Clear existing data
  await db.vote.deleteMany()
  await db.perk.deleteMany()
  await db.startup.deleteMany()

  // Create startups
  for (const startup of startups) {
    await db.startup.create({ data: startup })
  }

  console.log(`Created ${startups.length} startups`)

  // Create some perks for featured startups
  const featuredStartups = await db.startup.findMany({ where: { featured: true } })
  
  const perksData = [
    { startupId: featuredStartups[0]?.id, title: 'Free Trial', description: 'Get 3 months free on any plan', discount: '100% off for 3 months', url: '#' },
    { startupId: featuredStartups[0]?.id, title: 'Startup Discount', description: '50% off for early-stage startups', discount: '50% off first year', url: '#' },
    { startupId: featuredStartups[1]?.id, title: 'No Fees', description: 'Zero transaction fees for first $10K', discount: '$0 fees', url: '#' },
    { startupId: featuredStartups[2]?.id, title: 'Beta Access', description: 'Free beta access for Revolaunch community', discount: 'Free during beta', url: '#' },
    { startupId: featuredStartups[3]?.id, title: 'Demo License', description: 'Free 6-month demo license', discount: '6 months free', url: '#' },
  ].filter(p => p.startupId)

  for (const perk of perksData) {
    await db.perk.create({ data: perk })
  }

  console.log(`Created ${perksData.length} perks`)
  console.log('Seed complete!')
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect())
